# Generated by Django 5.2.15 on 2026-08-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Yechim kodi')),
                ('status', models.BooleanField(default=False, help_text="Agar hamma testlardan o'tgan bo'lsa True, aks holda False.", verbose_name='Muvaffaqiyatli yechildimi?')),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compile Error')], default='WA', max_length=4, verbose_name='Yakuniy hukm (Verdict)')),
                ('passed_test_count', models.PositiveIntegerField(default=0, verbose_name="O'tgan testlar soni")),
                ('total_test_count', models.PositiveIntegerField(default=0, verbose_name='Jami testlar soni')),
                ('execution_time', models.PositiveIntegerField(blank=True, help_text='Yechimning eng sekin ishlagan testidagi vaqti.', null=True, verbose_name='Ijro vaqti (ms)')),
                ('execution_memory', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ishlatilgan xotira (KB)')),
                ('test_results', models.JSONField(blank=True, default=list, help_text="Format: [{'idx': 1, 'ok': true, 'stdout': '...', 'stderr': null}, ...]", verbose_name='Batafsil test natijalari JSON')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuborilgan vaqt')),
                ('contest_registration', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — bu Practice/mustaqil yechim.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contestregistration', verbose_name='Musobaqa seansi')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.language', verbose_name='Dasturlash tili')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='Masala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📥 Yechim (Submission)',
                'verbose_name_plural': '📥 Yechimlar (Submissions)',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='submissions_user_id_1304bb_idx'), models.Index(fields=['problem', 'status'], name='submissions_problem_a647ed_idx'), models.Index(fields=['-submitted_at'], name='submissions_submitt_1f3aca_idx')],
            },
        ),
    ]
