# Generated by Django 5.2.15 on 2026-06-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Yuborilgan kod')),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='Muvaffaqiyatli yechilgan (✓)')),
                ('test_results', models.JSONField(blank=True, default=list, help_text='Har bir test case holati: [{"test_case": 1, "status": "passed", "time": 100}]', verbose_name='Test natijalari')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuborilgan vaqt')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bajarilish vaqti (ms)')),
                ('memory_used_kb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Xotira (KB)')),
                ('passed_test_count', models.PositiveIntegerField(default=0)),
                ('total_test_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.contest', verbose_name='Musobaqa (Contest)')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.language', verbose_name='Dasturlash tili')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='Masala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kod urinishi',
                'verbose_name_plural': 'Kod urinishlari',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'problem', 'status'], name='submissions_user_id_108b50_idx'), models.Index(fields=['user', 'contest'], name='submissions_user_id_3cb229_idx'), models.Index(fields=['status', 'submitted_at'], name='submissions_status_37dcdc_idx'), models.Index(fields=['contest', 'status'], name='submissions_contest_860f39_idx'), models.Index(fields=['problem', 'status', '-submitted_at'], name='submissions_problem_cc4893_idx')],
            },
        ),
    ]
