# Generated by Django 5.2.15 on 2026-07-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('problems', '0003_alter_testcase_options_and_more'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': '📥 Yechim (Submission)', 'verbose_name_plural': '📥 Yechimlar (Submissions)'},
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_user_id_108b50_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_user_id_3cb229_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_status_37dcdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_contest_860f39_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_problem_cc4893_idx',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='execution_time_ms',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory_used_kb',
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_memory',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ishlatilgan xotira (KB)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.PositiveIntegerField(blank=True, help_text='Yechimning eng sekin ishlagan testidagi vaqti.', null=True, verbose_name='Ijro vaqti (ms)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RE', 'Runtime Error'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compile Error')], default='WA', max_length=4, verbose_name='Yakuniy hukm (Verdict)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(verbose_name='Yechim kodi'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='passed_test_count',
            field=models.PositiveIntegerField(default=0, verbose_name="O'tgan testlar soni"),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=False, help_text="Agar hamma testlardan o'tgan bo'lsa True, aks holda False.", verbose_name='Muvaffaqiyatli yechildimi?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_results',
            field=models.JSONField(blank=True, default=list, help_text="Format: [{'idx': 1, 'ok': true, 'stdout': '...', 'stderr': null}, ...]", verbose_name='Batafsil test natijalari JSON'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_test_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami testlar soni'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='submissions_user_id_1304bb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status'], name='submissions_problem_a647ed_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submitted_at'], name='submissions_submitt_1f3aca_idx'),
        ),
    ]
