# Generated by Django 6.0.2 on 2026-06-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Kursning aniq va qisqa nomini kiriting', max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(blank=True, help_text='Kurs URL uchun avtomatik hosil qilinadi', unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Kurs haqida batafsil ma’lumot kiriting', verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='course/images/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Kursning asosiy narxi (masalan: 500000.00)', max_digits=10, verbose_name='Kurs narxi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text="Agar chegirma bo'lsa, yakuniy narxni kiriting", max_digits=10, null=True, verbose_name='Chegirmadagi narx')),
            ],
            options={
                'verbose_name': '✨ Kurs',
                'verbose_name_plural': '✨ Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Modulning qisqa nomi', max_length=200, verbose_name='Modul nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('course', models.ForeignKey(help_text='Modul qaysi kursga tegishli ekanligini tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='modullar', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': '📚 Kurs',
                'verbose_name_plural': '📚 Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Darslik nomi')),
                ('slug', models.SlugField(blank=True, help_text='URL uchun slug, avtomatik hosil qilinadi', verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('modul', models.ForeignKey(help_text='Qaysi kursga yozilmoqda', on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.modul', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': '📝 Dars',
                'verbose_name_plural': '📝 Darslar',
            },
        ),
        migrations.CreateModel(
            name='Enrilliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('is_paid', models.BooleanField(default=False, help_text='Agar kurs pullik bo‘lsa, bu yerda belgilash mumkin', verbose_name='To‘langan')),
                ('course', models.ForeignKey(help_text='Qaysi kursga yozilmoqda', on_delete=django.db.models.deletion.CASCADE, related_name='kursga_yozilishlar', to='courses.course', verbose_name='Kurs')),
                ('user', models.ForeignKey(help_text='Kursga yozilayotgan talaba', on_delete=django.db.models.deletion.CASCADE, related_name='kursga_yozilishlar', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '✨ Kursga yozilish',
                'verbose_name_plural': '✨ Kursga yozilishlar',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
