# Generated by Django 5.2.15 on 2026-08-06 07:21

import django.core.validators
import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('centers', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Kursning aniq va qisqa nomini kiriting', max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(blank=True, help_text='Kurs URL uchun avtomatik hosil qilinadi', unique=True, verbose_name='Slug')),
                ('description', mdeditor.fields.MDTextField(help_text='Kurs haqida batafsil ma’lumot kiriting', verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Kursning asosiy narxi (masalan: 500000.00)', max_digits=10, verbose_name='Kurs narxi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text="Agar chegirma bo'lsa, yakuniy narxni kiriting", max_digits=10, null=True, verbose_name='Chegirmadagi narx')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20)),
                ('total_modules_count', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('total_lessons_count', models.PositiveSmallIntegerField(default=0, verbose_name='Jami darslar soni')),
                ('total_test_count', models.PositiveSmallIntegerField(default=0, verbose_name='Jami test soni')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='centers.center', verbose_name='Markaz')),
                ('intro_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_courses', to='video.video', verbose_name='Kirish yoki qoidalar videosi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '✨ Kurs',
                'verbose_name_plural': '✨ Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Modulning qisqa nomi', max_length=200, verbose_name='Modul nomi')),
                ('slug', models.SlugField(blank=True, help_text="Modul URL uchun (ixtiyoriy, avtomatik hosil bo'ladi)", max_length=255, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ushbu blok dars interfeysida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Agar false bo'lsa, bu modul foydalanuvchilarga ko'rinmaydi.", verbose_name='Faol')),
                ('course', models.ForeignKey(help_text='Modul qaysi kursga tegishli ekanligini tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='modullar', to='courses.course', verbose_name='Kurs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📚 Kurs Bobi',
                'verbose_name_plural': '📚 Kurs boblari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=100, verbose_name='Darslik nomi')),
                ('slug', models.SlugField(blank=True, help_text='URL uchun slug, avtomatik hosil qilinadi', verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ushbu blok dars interfeysida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Agar false bo'lsa, bu dars foydalanuvchilarga ko'rinmaydi.", verbose_name='Faol')),
                ('total_tasks_count', models.PositiveSmallIntegerField(default=0, editable=False, help_text="Problem + Question(lesson) + Lecture sonlarining avtomatik yig'indisi.", verbose_name='Jami vazifalar soni')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='Taxminiy vaqt (daqiqa)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('modul', models.ForeignKey(help_text='Dars qaysi modulga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.modul', verbose_name='Modul')),
            ],
            options={
                'verbose_name': '📝 Dars',
                'verbose_name_plural': '📝 Darslar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='baseuser.baseuser')),
            ],
            options={
                'verbose_name': '✨ Kursga yozilish',
                'verbose_name_plural': '✨ Kursga yozilishlar',
                'indexes': [models.Index(fields=['user', '-created_at'], name='courses_enr_user_id_bf99b8_idx'), models.Index(fields=['course', 'is_paid'], name='courses_enr_course__2c1ed7_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Mavzu nomi (masalan: 1.2. *args va **kwargs argumentlari)', max_length=200, verbose_name='Mavzu sarlavhasi')),
                ('slug', models.SlugField(blank=True, help_text='URL va frontend navigatsiyasi uchun avtomatik hosil qilinadi.', max_length=255, verbose_name='Slug')),
                ('body', mdeditor.fields.MDTextField(blank=True, help_text="Markdown formatida ma'ruza matnini, qoidalarni va kod namunalarini yozing.", null=True, verbose_name="Ma'ruza matni (Konspekt)")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ushbu blok dars interfeysida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami')),
                ('reading_time', models.PositiveSmallIntegerField(default=0, help_text="Faqat matnni o'qish uchun taxminiy vaqt.", verbose_name="O'qish vaqti (daqiqa)")),
                ('xp', models.PositiveIntegerField(default=10, help_text="Ushbu ma'ruza muvaffaqiyatli yakunlanganda (video ko'rilganda yoki konspekt o'qib bo'linganda) foydalanuvchiga beriladigan XP miqdori. Faqat birinchi marta yakunlaganda beriladi. Qiymat diapazoni: 5 dan 20 gacha.", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='XP mukofoti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, help_text="Agar ushbu mavzuda video darslik bo'lsa, tanlang. Bo'sh qolsa, faqat matnli ma'ruza bo'ladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='video.video', verbose_name='Video darslik')),
                ('lesson', models.ForeignKey(help_text="Ushbu ma'ruza/video qaysi dars tarkibiga kirishini tanlang.", on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.lesson', verbose_name='Darslik')),
            ],
            options={
                'verbose_name': "📖 Ma'ruza va Video dars",
                'verbose_name_plural': "📖 Ma'ruzalar va Video darslar",
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['lesson', 'order'], name='courses_lec_lesson__cc3b79_idx'), models.Index(fields=['slug'], name='courses_lec_slug_f82d14_idx'), models.Index(fields=['video'], name='courses_lec_video_i_f98d5d_idx')],
            },
        ),
    ]
