# Generated by Django 5.2.15 on 2026-08-28 12:48

import django.core.validators
import django.db.models.deletion
import mdeditor.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('centers', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Kursning aniq va qisqa nomini kiriting', max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(blank=True, help_text='Kurs URL uchun avtomatik hosil qilinadi', unique=True, verbose_name='Slug')),
                ('description', mdeditor.fields.MDTextField(help_text='Kurs haqida batafsil ma’lumot kiriting', verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Kursning asosiy narxi (masalan: 500000.00)', max_digits=10, verbose_name='Kurs narxi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text="Agar chegirma bo'lsa, yakuniy narxni kiriting", max_digits=10, null=True, verbose_name='Chegirmadagi narx')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20)),
                ('total_modules_count', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('total_lessons_count', models.PositiveSmallIntegerField(default=0, verbose_name='Jami darslar soni')),
                ('total_test_count', models.PositiveSmallIntegerField(default=0, verbose_name='Jami test soni')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='centers.center', verbose_name='Markaz')),
                ('intro_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_courses', to='video.video', verbose_name='Kirish yoki qoidalar videosi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '✨ Kurs',
                'verbose_name_plural': '✨ Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('text', mdeditor.fields.MDTextField(help_text='Savol matnini Markdown formatida kiriting.', verbose_name='Savol matni')),
                ('instruction', models.TextField(blank=True, help_text="O'quvchiga beriladigan ko'rsatmani kiriting. Masalan: 'So'zlarni to'g'ri tartibda joylashtiring.'", verbose_name="Ko'rsatma")),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', "Ko'p tanlovli test"), ('ARRANGE_WORDS', "So'zlarni tartiblash"), ('MATCHING', 'Moslashtirish'), ('FILL_BLANKS', "Bo'shliqlarni to'ldirish")], help_text="Savol turini tanlang: Ko'p tanlovli test, So'zlarni tartiblash, Moslashtirish yoki Bo'shliqlarni to'ldirish.", max_length=30, verbose_name='Savol turi')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=10, verbose_name='Qiyinchilik darajasi')),
                ('explanation', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='Javob izohi')),
                ('xp', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)], verbose_name='XP mukofoti')),
                ('explanation_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_explanations', to='video.video', verbose_name='Savol video tahlili')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', mdeditor.fields.MDTextField(help_text='Markdown formatida javob variantining matnini kiriting.', verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(db_index=True, default=False, help_text="Agar ushbu variant savolning to'g'ri javobi bo'lsa, belgilang.", verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_choices', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.coursequestion', verbose_name='Tegishli savol')),
            ],
            options={
                'verbose_name': '🔘 Javob varianti',
                'verbose_name_plural': '✅ Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text="Bo'sh joyning gap ichidagi tartib raqamini kiriting.", verbose_name="Bo'sh joy tartibi")),
                ('case_sensitive', models.BooleanField(default=False, help_text='Yoqilsa, javob tekshirilganda harflar registri ham hisobga olinadi.', verbose_name='Katta-kichik harfga sezgir')),
                ('question', models.ForeignKey(help_text="Ushbu bo'sh joy tegishli bo'lgan savolni tanlang.", on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='courses.coursequestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': "◻️ Bo'sh joy",
                'verbose_name_plural': "◻️ Bo'sh joylar",
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArrangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Tartiblanadigan so'zni kiriting.", max_length=255, verbose_name="So'z")),
                ('correct_position', models.PositiveIntegerField(help_text="Ushbu so'zning to'g'ri gapdagi pozitsiyasini kiriting. Masalan: 1, 2, 3, 4.", verbose_name="To'g'ri pozitsiya")),
                ('question', models.ForeignKey(help_text="Ushbu so'z tegishli bo'lgan Arrange Words savolini tanlang.", on_delete=django.db.models.deletion.CASCADE, related_name='arrange_items', to='courses.coursequestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': "🔤 Tartiblanadigan so'z",
                'verbose_name_plural': "🔤 Tartiblanadigan so'zlar",
                'ordering': ['correct_position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text="Test yoki imtihon majmuasining to'liq sarlavhasi.", max_length=255, verbose_name='Test nomi')),
                ('slug', models.SlugField(blank=True, help_text="URL manzillari uchun avtomatik hosil bo'luvchi qisqa nom.", max_length=255, unique=True, verbose_name='Slug')),
                ('description', mdeditor.fields.MDTextField(blank=True, help_text="Markdown formatida masalaning to'liq shartini yozing.", null=True, verbose_name='test sharti (Matn)')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Testni yechish uchun foydalanuvchiga beriladigan umumiy vaqt (daqiqa hisobida).', verbose_name='Davomiyligi (daqiqa)')),
                ('question_count', models.PositiveIntegerField(default=0, help_text="Ushbu test tarkibiga qo'shilgan jami umumiy savollar soni (avtomatik yoki qo'lda yangilanadi).", verbose_name='Bazasidagi jami savollar soni')),
                ('min_pass_percentage', models.PositiveIntegerField(default=60, help_text="Testdan muvaffaqiyatli o'tish uchun talaba to'plashi kerak bo'lgan eng kam foiz ko'rsatkichi (0-100).", validators=[django.core.validators.MaxValueValidator(100)], verbose_name="O'tish foizi")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Test talabalarga ko'rinishi yoki vaqtincha yashirib qo'yilishi uchun boshqaruv belgisi.", verbose_name='Faol')),
                ('penalty_coefficient', models.FloatField(default=0.33, help_text="Noto'g'ri javoblar uchun jarima koeffitsiyenti. Masalan: 0.33 yozilsa, 3 ta xato javob 1 ta to'g'ri javob ballini olib ketadi.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Jarima koeffitsiyenti (K)')),
                ('max_lifelines', models.PositiveIntegerField(default=3, help_text="Talaba test davomida foydalanishi mumkin bo'lgan yordam vositalari (Lifeline) soni.", verbose_name='Maksimal Reler (Lifeline) soni')),
                ('intro_video', models.ForeignKey(blank=True, help_text="Testni boshlashdan oldin ko'rsatiladigan yo'riqnoma yoki tushuntirish videosi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_video', to='video.video', verbose_name='Kirish yoki qoidalar videosi')),
                ('owner', models.ForeignKey(help_text="Ushbu test majmuasini yaratgan va unga egalik qiluvchi o'qituvchi/admin.", on_delete=django.db.models.deletion.CASCADE, related_name='course_tests', to=settings.AUTH_USER_MODEL, verbose_name="Yaratuvchi o'qituvchi")),
            ],
            options={
                'verbose_name': '📋 Test',
                'verbose_name_plural': '📋 Testlar',
                'ordering': ['-id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.coursetest', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='CourseTestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Har bir test topshirish seansi uchun unikal UUID identifikator.', primary_key=True, serialize=False, verbose_name='Seans ID')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text="Talaba tomonidan ushbu seansda to'g'ri belgilangan savollarning umumiy miqdori.", verbose_name="To'g'ri javoblar soni")),
                ('wrong_count', models.PositiveIntegerField(default=0, help_text="Talaba xato belgilagan yoki noto'g'ri topshirgan savollar soni.", verbose_name="Noto'g'ri javoblar soni")),
                ('unanswered_count', models.PositiveIntegerField(default=0, help_text="Talaba tomonidan belgilamasdan o'tkazib yuborilgan yoki vaqt yetmay umuman ochilmagan savollar soni.", verbose_name='Javobsiz qoldirilganlar soni')),
                ('total_xp_earned', models.PositiveIntegerField(db_index=True, default=0, help_text="Ushbu urinish natijasida foydalanuvchining global profiliga qo'shish uchun hisoblangan butun sonli mukofot balli.", verbose_name='Yutilgan XP ball')),
                ('lifelines_used', models.PositiveIntegerField(default=0, help_text="Ushbu seansda foydalanuvchi hozirgacha ishlatgan lifeline'lar soni (faqat serverda hisoblanadi, frontend hisoblagichiga ishonilmaydi).", verbose_name='Ishlatilgan Reler (Lifeline) soni')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Foydalanuvchi testni yechishni boshlagan aniq sana va vaqt.', verbose_name='Boshlangan vaqti')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Test yakunlangan yoki vaqt tugashi sababli tizim tomonidan yopilgan aniq vaqt.', null=True, verbose_name='Yakunlangan vaqti')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.coursetest', verbose_name='Test')),
                ('user', models.ForeignKey(help_text="Testni topshirayotgan (tizimda faol bo'lgan) talaba.", on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '⏱ Test Seansi',
                'verbose_name_plural': '⏱ Test Seanslari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(blank=True, help_text='Matching, Arrange Words yoki Fill Blanks turidagi savollar uchun talaba javobi.', null=True, verbose_name='Javob (JSON)')),
                ('is_correct', models.BooleanField(blank=True, help_text="Tekshirilgandan so'ng avtomatik hisoblab qo'yiladi (null = hali tekshirilmagan).", null=True, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Talaba joriy savolga javob tugmasini bosgan aniq vaqt.', verbose_name='Javob berilgan vaqt')),
                ('choice', models.ForeignKey(blank=True, help_text="Talaba tomonidan belgilangan javob varianti (bo'sh qolsa = javobsiz qoldirilgan).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursechoice', verbose_name='Tanlangan variant')),
                ('question', models.ForeignKey(help_text='Javob berilgan test yoki darslik savoli.', on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='courses.coursequestion', verbose_name='Savol')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.coursetestsession', verbose_name='Test seansi')),
                ('user', models.ForeignKey(help_text='Javob bergan talaba.', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '🎯 Foydalanuvchi Javobi',
                'verbose_name_plural': '🎯 Foydalanuvchi Javoblari',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='baseuser.baseuser')),
            ],
            options={
                'verbose_name': '✨ Kursga yozilish',
                'verbose_name_plural': '✨ Kursga yozilishlar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=100, verbose_name='Darslik nomi')),
                ('slug', models.SlugField(blank=True, help_text='URL uchun slug, avtomatik hosil qilinadi', verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=1, help_text='1 dan boshlanadigan natural son. Masalan: 1, 2, 3, 4...', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Agar false bo'lsa, bu dars foydalanuvchilarga ko'rinmaydi.", verbose_name='Faol')),
                ('total_tasks_count', models.PositiveSmallIntegerField(default=0, editable=False, help_text="Problem + Question(lesson) + Lecture sonlarining avtomatik yig'indisi.", verbose_name='Jami vazifalar soni')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='Taxminiy vaqt (daqiqa)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📚 Darslik',
                'verbose_name_plural': '📚 Darslik',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Mavzu nomi (masalan: 1.2. *args va **kwargs argumentlari)', max_length=200, verbose_name='Mavzu sarlavhasi')),
                ('slug', models.SlugField(blank=True, help_text='URL va frontend navigatsiyasi uchun avtomatik hosil qilinadi.', max_length=255, verbose_name='Slug')),
                ('body', mdeditor.fields.MDTextField(blank=True, help_text="Markdown formatida ma'ruza matnini, qoidalarni va kod namunalarini yozing.", null=True, verbose_name="Ma'ruza matni (Konspekt)")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ushbu blok dars interfeysida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami')),
                ('reading_time', models.PositiveSmallIntegerField(default=0, help_text="Faqat matnni o'qish uchun taxminiy vaqt.", verbose_name="O'qish vaqti (daqiqa)")),
                ('xp', models.PositiveIntegerField(default=10, help_text="Ushbu ma'ruza muvaffaqiyatli yakunlanganda (video ko'rilganda yoki konspekt o'qib bo'linganda) foydalanuvchiga beriladigan XP miqdori. Faqat birinchi marta yakunlaganda beriladi. Qiymat diapazoni: 5 dan 20 gacha.", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='XP mukofoti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, help_text="Agar ushbu mavzuda video darslik bo'lsa, tanlang. Bo'sh qolsa, faqat matnli ma'ruza bo'ladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='video.video', verbose_name='Video darslik')),
                ('lesson', models.ForeignKey(help_text="Ushbu ma'ruza/video qaysi dars tarkibiga kirishini tanlang.", on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.lesson', verbose_name='Darslik')),
            ],
            options={
                'verbose_name': "📖 Ma'ruza va Video dars",
                'verbose_name_plural': "📖 Ma'ruzalar va Video darslar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson', verbose_name='Darslik'),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(help_text='Moslashtirishning chap tomonidagi elementni kiriting.', max_length=255, verbose_name='Chap tomon')),
                ('right', models.CharField(help_text='Chap tomonga mos keladigan javobni kiriting.', max_length=255, verbose_name="O'ng tomon")),
                ('order', models.PositiveIntegerField(default=0, help_text='Juftlikning savol ichidagi tartibini belgilang.', verbose_name='Tartib raqami')),
                ('question', models.ForeignKey(help_text="Ushbu juftlik tegishli bo'lgan Matching savolini tanlang.", on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='courses.coursequestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': '🔗 Moslashtirish juftligi',
                'verbose_name_plural': '🔗 Moslashtirish juftliklari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(help_text='Modulning qisqa nomi', max_length=200, verbose_name='Modul nomi')),
                ('slug', models.SlugField(blank=True, help_text="Modul URL uchun (ixtiyoriy, avtomatik hosil bo'ladi)", max_length=255, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ushbu blok dars interfeysida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Agar false bo'lsa, bu modul foydalanuvchilarga ko'rinmaydi.", verbose_name='Faol')),
                ('course', models.ForeignKey(help_text='Modul qaysi kursga tegishli ekanligini tanlang', on_delete=django.db.models.deletion.CASCADE, related_name='modullar', to='courses.course', verbose_name='Kurs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📚 Kurs Bobi',
                'verbose_name_plural': '📚 Kurs boblari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='modul',
            field=models.ForeignKey(help_text='Dars qaysi modulga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.modul', verbose_name='Modul'),
        ),
        migrations.AddField(
            model_name='coursetest',
            name='modul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='courses.modul', verbose_name='Bob (Modul)'),
        ),
        migrations.CreateModel(
            name='BlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(help_text="Ushbu bo'sh joy uchun qabul qilinadigan to'g'ri javobni kiriting.", max_length=255, verbose_name="To'g'ri javob")),
                ('blank', models.ForeignKey(help_text="Javob tegishli bo'lgan bo'sh joyni tanlang.", on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.blank', verbose_name="Bo'sh joy")),
            ],
            options={
                'verbose_name': "◻️ Bo'sh joy javobi",
                'verbose_name_plural': "◻️ Bo'sh joy javoblari",
                'constraints': [models.UniqueConstraint(fields=('blank', 'answer'), name='unique_answer_per_blank')],
            },
        ),
        migrations.AddConstraint(
            model_name='coursechoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_course_correct_choice'),
        ),
        migrations.AddConstraint(
            model_name='blank',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='unique_blank_position_per_question'),
        ),
        migrations.AddConstraint(
            model_name='arrangeitem',
            constraint=models.UniqueConstraint(fields=('question', 'correct_position'), name='unique_arrange_position_per_question'),
        ),
        migrations.AddIndex(
            model_name='coursetestsession',
            index=models.Index(fields=['user', 'test'], name='courses_cou_user_id_c67083_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetestsession',
            index=models.Index(fields=['-started_at'], name='courses_cou_started_92735b_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseuserresponse',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_response_per_question_per_session'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', '-created_at'], name='courses_enr_user_id_bf99b8_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'is_paid'], name='courses_enr_course__2c1ed7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['lesson', 'order'], name='courses_lec_lesson__cc3b79_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['slug'], name='courses_lec_slug_f82d14_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['video'], name='courses_lec_video_i_f98d5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_lecture_order_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='coursequestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('test__isnull', True)), models.Q(('lesson__isnull', True), ('test__isnull', False)), _connector='OR'), name='question_belongs_to_lesson_xor_test'),
        ),
        migrations.AddConstraint(
            model_name='matchingpair',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_matching_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='modul',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('modul', 'order'), name='unique_lesson_order_per_module'),
        ),
    ]
