# Generated by Django 5.2.15 on 2026-08-29 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequestion',
            name='xp_is_custom',
            field=models.BooleanField(default=False, editable=False, verbose_name="XP qo'lda o'zgartirilganmi"),
        ),
        migrations.AlterField(
            model_name='arrangeitem',
            name='correct_position',
            field=models.PositiveIntegerField(help_text="Ushbu so'zning to'g'ri gapdagi pozitsiyasini kiriting (1 dan boshlab). Masalan: 1, 2, 3, 4.", validators=[django.core.validators.MinValueValidator(1)], verbose_name="To'g'ri pozitsiya"),
        ),
        migrations.AlterField(
            model_name='blank',
            name='position',
            field=models.PositiveIntegerField(help_text="Bo'sh joyning gap ichidagi tartib raqamini kiriting (1 dan boshlab).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="Bo'sh joy tartibi"),
        ),
        migrations.AddConstraint(
            model_name='arrangeitem',
            constraint=models.CheckConstraint(condition=models.Q(('correct_position__gte', 1)), name='arrange_item_position_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='blank',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='blank_position_gte_1'),
        ),
    ]
