# Generated by Django 5.2.15 on 2026-06-28 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='xp',
            field=models.PositiveIntegerField(default=10, help_text="Ushbu ma'ruza muvaffaqiyatli yakunlanganda (video ko'rilganda yoki konspekt o'qib bo'linganda) foydalanuvchiga beriladigan XP miqdori. Faqat birinchi marta yakunlaganda beriladi. Qiymat diapazoni: 5 dan 20 gacha.", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='XP mukofoti'),
        ),
    ]
