# Generated by Django 5.2.15 on 2026-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lecture_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ushbu blok dars interfeysida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami'),
        ),
    ]
