# Generated by Django 5.2.15 on 2026-08-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('courses', '0002_coursequestion_xp_is_custom_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursetestsession',
            index=models.Index(fields=['user', 'test', '-total_xp_earned'], name='test_session_best_lookup'),
        ),
    ]
