# Generated by Django 5.2.15 on 2026-08-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursetestsession_test_session_best_lookup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursechoice',
            name='unique_course_correct_choice',
        ),
        migrations.AddField(
            model_name='courseuserresponse',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, help_text='MULTIPLE_CHOICE savol uchun talaba tanlagan bir yoki bir nechta javob variantlari.', related_name='multiple_choice_responses', to='courses.coursechoice', verbose_name='Tanlangan variantlar'),
        ),
        migrations.AlterField(
            model_name='coursequestion',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Bitta tanlov'), ('MULTIPLE_CHOICE', "Ko'p tanlov"), ('ARRANGE_WORDS', "So'zlarni tartiblash"), ('MATCHING', 'Moslashtirish'), ('FILL_BLANKS', "Bo'shliqlarni to'ldirish")], help_text="Savol turini tanlang: Ko'p tanlovli test, So'zlarni tartiblash, Moslashtirish yoki Bo'shliqlarni to'ldirish.", max_length=30, verbose_name='Savol turi'),
        ),
        migrations.AlterField(
            model_name='courseuserresponse',
            name='answer_data',
            field=models.JSONField(blank=True, help_text="Matching, Arrange Words yoki Fill Blanks savollarining javob ma'lumotlari.", null=True, verbose_name='Javob (JSON)'),
        ),
        migrations.AlterField(
            model_name='courseuserresponse',
            name='choice',
            field=models.ForeignKey(blank=True, help_text='SINGLE_CHOICE savol uchun talaba tanlagan bitta javob varianti.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_choice_responses', to='courses.coursechoice', verbose_name='Tanlangan variant'),
        ),
    ]
