# Generated by Django 5.2.15 on 2026-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='total_tasks_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text="Problem + Question(lesson) + Lecture sonlarining avtomatik yig'indisi.", verbose_name='Jami vazifalar soni'),
        ),
    ]
