# Generated by Django 5.2.15 on 2026-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_coursechoice_unique_course_correct_choice_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursequestion',
            name='question_belongs_to_lesson_xor_test',
        ),
        migrations.AddField(
            model_name='coursequestion',
            name='is_embeddable',
            field=models.BooleanField(default=False, help_text="Agar yoqilgan bo'lsa, savol description/body ichida {{savol:id:get}} placeholder orqali ishlatilishi mumkin.", verbose_name='Description ichida ishlatish mumkin'),
        ),
    ]
