# Generated by Django 5.2.15 on 2026-08-06 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Markaz nomi')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_centers', to=settings.AUTH_USER_MODEL, verbose_name='Markaz direktori')),
            ],
            options={
                'verbose_name': "🏢 O'quv Markaz",
                'verbose_name_plural': "🏢 O'quv Markazlar",
                'ordering': ['name'],
            },
        ),
    ]
