# Generated by Django 5.2.15 on 2026-08-06 07:21

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('centers', '0001_initial'),
        ('courses', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Piston API qabul qiladigan til nomi (masalan: python, csharp, cpp)', max_length=250, unique=True, verbose_name='Til nomi')),
                ('version', models.CharField(help_text='Piston API dagi aniq versiyasi (masalan: 3.12.0, 10.2.0)', max_length=50, verbose_name='Versiyasi')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Taxalluslar')),
            ],
            options={
                'verbose_name': '💻 Dasturlash tili',
                'verbose_name_plural': '⚙️ Dasturlash tillari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalalar guruhlanadigan kategoriya nomi (masalan: Algoritmlar)', max_length=250, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(help_text="URL manzili uchun avtomatik hosil bo'ladi", max_length=500, unique=True, verbose_name='Slug')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
            ],
            options={
                'verbose_name': '📁 Kategoriya',
                'verbose_name_plural': '📂 Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalaning qisqa va aniq nomi.', max_length=200, verbose_name='Masala sarlavhasi')),
                ('slug', models.SlugField(blank=True, help_text='URL manzili uchun avtomatik shakllanadi.', max_length=250, unique=True, verbose_name='Slug')),
                ('description', mdeditor.fields.MDTextField(help_text="Markdown formatida masalaning to'liq shartini yozing.", verbose_name='Masala sharti (Matn)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Saytda talabalarga ko'rinishi yoki yashirin bo'lishi.", verbose_name='Aktivlik holati')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', help_text='Masalaning murakkablik darajasini belgilang.', max_length=10, verbose_name='Qiyinchilik darajasi')),
                ('time_limit', models.IntegerField(default=2000, help_text='Millisekundlarda belgilang (100 ms dan 3000 ms gacha). Piston API maksimal 3000 ms qabul qiladi. Masalan: 2000 = 2 sekund.', validators=[django.core.validators.MinValueValidator(100, message="Vaqt cheklovi kamida 100 ms bo'lishi kerak."), django.core.validators.MaxValueValidator(3000, message='Vaqt cheklovi Piston API limiti sababli 3000 ms dan oshmasligi kerak.')], verbose_name='Vaqt cheklovi')),
                ('memory_limit', models.IntegerField(default=256, help_text="Megabaytlarda belgilang (1 MB dan 512 MB gacha). Piston API xotira limitini qo'llab-quvvatlaydi. Masalan: 256 = 256 MB.", validators=[django.core.validators.MinValueValidator(1, message="Xotira cheklovi kamida 1 MB bo'lishi kerak."), django.core.validators.MaxValueValidator(512, message='Xotira cheklovi 512 MB dan oshmasligi kerak.')], verbose_name='Xotira cheklovi')),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Layklar soni')),
                ('dislikes_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Dislayklar soni')),
                ('xp', models.PositiveIntegerField(default=10, help_text="Ushbu masala birinchi marta to'g'ri (Accepted) yechilganda foydalanuvchiga beriladigan XP miqdori. Agar masala biror Contest doirasida yechilsa, bu qiymat ContestRegistration.total_xp_earned ga FAQAT birinchi to'g'ri yechim uchun qo'shiladi (qayta yechilsa, qo'shimcha XP berilmaydi).10<=xp<=100", validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='XP mukofoti')),
                ('solved_count', models.PositiveIntegerField(default=0, verbose_name='Yechilgan marta')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Urinishlar soni')),
                ('category', models.ForeignKey(blank=True, help_text='Masala qaysi ruknga tegishli?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.category', verbose_name='Kategoriya')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='centers.center', verbose_name='Markaz')),
                ('language', models.ManyToManyField(blank=True, help_text='Ushbu masalani qaysi dasturlash tillarida yechish mumkin?', related_name='problems', to='problems.language', verbose_name='Ruxsat berilgan tillar')),
                ('lesson', models.ForeignKey(blank=True, help_text='Ushbu masala qaysi darsga tegishli ekanligini tanlang.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='courses.lesson', verbose_name='Darslik')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
                ('solution_video', models.ForeignKey(blank=True, help_text="Masalaning kodli yoki g'oyaviy yechimi tushuntirilgan videoni biriktiring.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='video.video', verbose_name='Yechim video tahlili')),
            ],
            options={
                'verbose_name': '💡 Masala',
                'verbose_name_plural': '🧠 Masalalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', mdeditor.fields.MDTextField(help_text="Talaba qiynalganda ko'rinadigan qisqa ko'rsatma yoki shama.", verbose_name='Yordam matni')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem', verbose_name='Masala')),
            ],
            options={
                'verbose_name': '🔑 Yordam',
                'verbose_name_plural': '💡 Yordamlar',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', mdeditor.fields.MDTextField(help_text="Masalani yanada optimallashtirish uchun qo'shimcha vazifa (Follow-up).", verbose_name="Qo'shimcha shart")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='problems.problem', verbose_name='Masala')),
            ],
            options={
                'verbose_name': '🎯 Topshiriq',
                'verbose_name_plural': '⚔️ Topshiriqlar',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Qidiruvni osonlashtirish uchun kalit so'z (masalan: arrays, string)", max_length=50, unique=True, verbose_name='Teg nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
            ],
            options={
                'verbose_name': '🏷️ Teg',
                'verbose_name_plural': '🔖 Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Masalaga mos keluvchi teglar yoki mavzularni kiriting.', related_name='problems', to='problems.tags', verbose_name='Teglar'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_txt', models.TextField(help_text="Yashirin tekshiruv uchun kirish ma'lumotlari.", verbose_name='Test Input')),
                ('output_txt', models.TextField(help_text="Ushbu kirish ma'lumotiga mos keluvchi aniq to'g'ri javob.", verbose_name='Test Output')),
                ('explanation', models.TextField(blank=True, help_text='Ushbu test qanday ishlashi haqida ixtiyoriy tushuntirish.', null=True, verbose_name='Izoh')),
                ('is_sample', models.BooleanField(default=False, help_text="Agar true bo'lsa, bu test foydalanuvchiga masala shartida ko'rinadi.", verbose_name='Namuna testmi?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Testlarni ketma-ketlikda tekshirish uchun tartib raqam.', verbose_name='Tartib raqami')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem', verbose_name='Masala')),
            ],
            options={
                'verbose_name': '🧪 Test case',
                'verbose_name_plural': '✅ Test caselar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField(default=True, help_text='Belgilansa 👍 (Like), belgilanmasa 👎 (Dislike) hisoblanadi.', verbose_name='Reaksiya turi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_likes', to='problems.problem', verbose_name='Masala')),
            ],
            options={
                'verbose_name': '👍 Reaksiya',
                'verbose_name_plural': '👍 Reaksiyalar',
                'unique_together': {('problem', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField(help_text='Foydalanuvchi kod yozishni boshlashi uchun tayyor funksiya strukturasi (LeetCode kabi).', verbose_name='Funksiya shabloni')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language', verbose_name='Dasturlash tili')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='problems.problem', verbose_name='Masala')),
            ],
            options={
                'verbose_name': '🧩 Funksiya shabloni',
                'verbose_name_plural': '🛠️ Funksiya shablonlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_code', models.TextField(blank=True, help_text="Foydalanuvchi kodiga yashirincha tepadan qo'shiladigan kutubxonalar yoki driver kod.", null=True, verbose_name='Tepa qism kodi (Header)')),
                ('bottom_code', models.TextField(help_text='Foydalanuvchi yozgan funksiyani chaqirib, test qiluvchi main kod qismi.', verbose_name='Pastki qism kodi (Footer/Main)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_language', to='problems.language', verbose_name='Dasturlash tili')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_problem', to='problems.problem', verbose_name='Masala')),
            ],
            options={
                'verbose_name': '🚀 Kod testi',
                'verbose_name_plural': '⚙️ Kod testlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active', 'difficulty'], name='problems_pr_is_acti_bcc8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_19f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem', 'order'], name='problems_te_problem_83c59f_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['is_sample'], name='problems_te_is_samp_67827c_idx'),
        ),
    ]
