# Generated by Django 5.2.15 on 2026-06-15 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        ('courses', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': '📁 Kategoriya',
                'verbose_name_plural': '📂 Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': '💻 Dasturlash tili',
                'verbose_name_plural': '⚙️ Dasturlash tillari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '🏷️ Teg',
                'verbose_name_plural': '🔖 Teglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('problem_type', models.CharField(choices=[('darslik', 'darslik'), ('test', 'test'), ('problem', 'problem')], default='problem', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=10)),
                ('xp', models.PositiveIntegerField(default=10, help_text="Ushbu masalani yechgan foydalanuvchiga beriladigan ball (XP). Agar 0 qoldirilsa, qiyinchilikka qarab avtomat belgilanadi: Oson: 100, O'rtacha: 250, Qiyin: 500.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tajriba ochkosi (XP)')),
                ('time_limit', models.IntegerField(blank=True, default=2000, help_text='Millisekundlarda', null=True)),
                ('memory_limit', models.IntegerField(blank=True, default=256, help_text='Megabaytlarda', null=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.category')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contests.contest')),
                ('language', models.ManyToManyField(blank=True, related_name='problems', to='problems.language')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='courses.lesson')),
                ('solution_video', models.ForeignKey(blank=True, help_text="Ushbu masalaning kodli yoki g'oyaviy yechimi tushuntirilgan videoni biriktiring.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='video.video', verbose_name='Yechim video tahlili')),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tags')),
            ],
            options={
                'verbose_name': '💡 Masala',
                'verbose_name_plural': '🧠 Masalalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem')),
            ],
            options={
                'verbose_name': '🔑 Yordam',
                'verbose_name_plural': '💡 Yordamlar',
            },
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_txt', models.TextField(help_text="Kirish ma'lumotlari, masalan: '[2,7,11,15]\\n9'")),
                ('output_txt', models.TextField(help_text="Chiqish ma'lumotlari, masalan: '[0,1]'")),
                ('explanation', models.TextField(help_text='Tushuntirish matni')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='problems.problem')),
            ],
            options={
                'verbose_name': '📝 Misol',
                'verbose_name_plural': '📋 Misollar',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='problems.problem')),
            ],
            options={
                'verbose_name': '🎯 Topshiriq',
                'verbose_name_plural': '⚔️ Topshiriqlar',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_txt', models.TextField(help_text='Test Input')),
                ('output_txt', models.TextField(help_text='Chiqish Output')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'verbose_name': '🧪 Test case',
                'verbose_name_plural': '✅ Test caselar',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField(default=True, help_text='True = Like, False = Dislike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_likes', to='problems.problem', verbose_name='Masala')),
            ],
            options={
                'verbose_name': '👍 Reaksiya',
                'verbose_name_plural': '👍 Reaksiyalar',
                'unique_together': {('problem', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='problems.problem')),
            ],
            options={
                'verbose_name': '🧩 Funksiya shabloni',
                'verbose_name_plural': '🛠️ Funksiya shablonlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_code', models.TextField(blank=True, null=True)),
                ('bottom_code', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_language', to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_problem', to='problems.problem')),
            ],
            options={
                'verbose_name': '🚀 Kod testi',
                'verbose_name_plural': '⚙️ Kod testlari',
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active', 'difficulty'], name='problems_pr_is_acti_bcc8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_19f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem'], name='problems_te_problem_71dd6a_idx'),
        ),
    ]
