# Generated by Django 5.2.15 on 2026-06-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
    ]
