# Generated by Django 5.2.15 on 2026-07-05 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_language_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['order', 'id'], 'verbose_name': '🧪 Test case', 'verbose_name_plural': '✅ Test caselar'},
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='problems_te_problem_71dd6a_idx',
        ),
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True, help_text='Ushbu test qanday ishlashi haqida ixtiyoriy tushuntirish.', null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False, help_text="Agar true bo'lsa, bu test foydalanuvchiga masala shartida ko'rinadi.", verbose_name='Namuna testmi?'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Testlarni ketma-ketlikda tekshirish uchun tartib raqam.', verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['problem', 'order'], name='problems_te_problem_83c59f_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['is_sample'], name='problems_te_is_samp_67827c_idx'),
        ),
    ]
