# Generated by Django 5.2.15 on 2026-06-28 02:02

import django.core.validators
import django.db.models.deletion
import mdeditor.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Tanlovning to'liq, foydalanuvchilarga ko'rinadigan nomi. Masalan: «Matematika Olimpiadasi 2026».", max_length=200, verbose_name='Tanlov nomi')),
                ('slug', models.SlugField(blank=True, help_text="Lotin harflarida, bo'sh joysiz manzil qismi. Bo'sh qoldirilsa, tanlov nomidan avtomat hosil qilinadi.", max_length=200, unique=True, verbose_name='URL nomi (slug)')),
                ('description', mdeditor.fields.MDTextField(blank=True, help_text="Markdown formatida yozilgan to'liq tavsif: qoidalar, talablar, mukofotlar haqida umumiy ma'lumot.", null=True, verbose_name='Tavsif')),
                ('cover_image', models.ImageField(blank=True, help_text="Tanlov kartochkasi va sahifa boshida ko'rsatiladigan banner rasm (tavsiya etiladi: 1200x630px).", null=True, upload_to='contests/covers/%Y/%m/', verbose_name='Muqova rasmi')),
                ('type', models.CharField(choices=[('open', 'Ochiq Tanlov (Public)'), ('private', 'Yopiq Tanlov (Private)')], db_index=True, default='open', editable=False, help_text="Avtomat hisoblanadi: agar «Kirish kaliti» kiritilgan bo'lsa — Yopiq, aks holda — Ochiq.", max_length=10, verbose_name='Tanlov turi')),
                ('status', models.CharField(choices=[('upcoming', 'Kutilmoqda'), ('ongoing', 'Davom etmoqda'), ('ended', 'Yakunlangan')], db_index=True, default='upcoming', help_text='Boshlanish/tugash vaqtiga qarab `save()` chaqirilganda avtomat yangilanadi.', max_length=10, verbose_name='Holati')),
                ('start_time', models.DateTimeField(help_text='Tanlov aynan shu vaqtda boshlanadi va ishtirokchilar testga kira oladi.', verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(help_text='Bu vaqtdan keyin tanlov avtomat ravishda yakunlangan deb belgilanadi va kirish yopiladi.', verbose_name='Tugash vaqti')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text="Ishtirokchilar shu vaqtgacha ro'yxatdan o'tishi shart. Bo'sh qoldirilsa, boshlanish vaqti bilan teng deb hisoblanadi.", null=True, verbose_name="Ro'yxatdan o'tish muddati")),
                ('max_participants', models.PositiveIntegerField(blank=True, default=0, help_text="0 yoki bo'sh — chegara yo'q, istalgancha kishi qatnashishi mumkin.", verbose_name='Maksimal ishtirokchilar soni')),
                ('questions_count', models.PositiveIntegerField(default=0, help_text='Ushbu tanlovda ishtirokchiga taqdim etiladigan savollarning umumiy soni.', verbose_name='Savollar soni')),
                ('pass_score_percent', models.PositiveIntegerField(default=50, help_text="Sertifikat olish yoki «muvaffaqiyatli» deb hisoblanish uchun zarur bo'lgan eng kam foiz (0-100).", verbose_name="O'tish balli (%)")),
                ('access_key', models.CharField(blank=True, help_text="Faqat yopiq tanlovlar uchun. Kiritilsa, tanlov turi avtomat «Yopiq»ga o'zgaradi va shu kalitni bilganlar kira oladi.", max_length=100, null=True, verbose_name='Kirish kaliti')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa, tanlov hech qayerda (status «ended» bo'lsa ham) foydalanuvchilarga ko'rsatilmaydi.", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Oxirgi o'zgartirilgan sana")),
                ('intro_video', models.ForeignKey(blank=True, help_text="Ishtirokchilar tanlovga kirishdan oldin ko'radigan tushuntirish/qoidalar videosi (ixtiyoriy).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='video.video', verbose_name='Kirish yoki qoidalar videosi')),
                ('owner', models.ForeignKey(help_text='Ushbu tanlovni yaratgan va boshqaradigan staff foydalanuvchi.', on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL, verbose_name='Tashkilotchi (admin)')),
            ],
            options={
                'verbose_name': '🏆 Musobaqa',
                'verbose_name_plural': '🏁 Musobaqalar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Noutbuk, Sertifikat, Oltin medal.', max_length=200, verbose_name='Mukofot nomi')),
                ('rank_target', models.PositiveIntegerField(help_text="Ushbu mukofot nechanchi o'rin egasiga beriladi (masalan: 1).", validators=[django.core.validators.MinValueValidator(1)], verbose_name="Munosib o'rin")),
                ('monetary_value', models.DecimalField(blank=True, decimal_places=2, help_text="Mukofotning pul ko'rinishidagi taxminiy qiymati. Statistik hisobotlar uchun, ixtiyoriy.", max_digits=12, null=True, verbose_name="Taxminiy qiymati (so'm)")),
                ('image', models.ImageField(blank=True, help_text='Mukofotning rasmi (masalan, noutbuk yoki sertifikat namunasi).', null=True, upload_to='contests/prizes/%Y/%m/', verbose_name='Mukofot rasmi')),
                ('description', mdeditor.fields.MDTextField(blank=True, help_text="Mukofot haqida batafsil ma'lumot, shartlar yoki izohlar.", null=True, verbose_name="Qo'shimcha tavsif")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('contest', models.ForeignKey(help_text="Mukofot tegishli bo'lgan tanlov.", on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='contests.contest', verbose_name='Musobaqa')),
                ('owner', models.ForeignKey(help_text='Mukofotni tizimga kiritgan staff foydalanuvchi.', on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan admin")),
            ],
            options={
                'verbose_name': '🎁 Mukofot',
                'verbose_name_plural': '🎁 Mukofotlar',
                'ordering': ['rank_target'],
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Har bir seans uchun noyob UUID identifikator.', primary_key=True, serialize=False, verbose_name='Identifikator')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', "Muddati o'tgan"), ('disqualified', 'Diskvalifikatsiya qilingan')], db_index=True, default='in_progress', help_text="Seans hozirgi holati: jarayonda, yakunlangan, muddati o'tgan yoki diskvalifikatsiya qilingan.", max_length=20, verbose_name='Holati')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text="Ishtirokchi to'g'ri javob bergan savollar soni.", verbose_name="To'g'ri javoblar soni")),
                ('wrong_count', models.PositiveIntegerField(default=0, help_text="Ishtirokchi noto'g'ri javob bergan savollar soni.", verbose_name="Noto'g'ri javoblar soni")),
                ('unanswered_count', models.PositiveIntegerField(default=0, help_text='Ishtirokchi umuman javob bermagan savollar soni.', verbose_name='Javobsiz qoldirilgan savollar soni')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Ishtirokchi testni yechishga sarflagan umumiy vaqt, soniyalarda.', verbose_name='Sarflangan vaqt (soniya)')),
                ('total_xp_earned', models.PositiveIntegerField(db_index=True, default=0, help_text="Foydalanuvchi ushbu testdan ishlagan toza XP ballari. Reyting shu maydon bo'yicha tuziladi.", verbose_name='Ushbu musobaqa jami XP balli')),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, help_text="Tanlov yakunlangach hisoblangan, ushbu ishtirokchining umumiy reytingdagi o'rni (1 — birinchi o'rin).", null=True, verbose_name="Musobaqadagi o'rni")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Ishtirokchi testni boshlagan paytdagi IP manzili. Firibgarlikni aniqlash uchun foydali.', null=True, verbose_name='IP manzil')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text="Foydalanuvchi tanlovga ro'yxatdan o'tib, testni boshlagan vaqt.", verbose_name='Boshlangan sana')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text="Test yakunlangan yoki muddati tugagan payt. Avtomat to'ldiriladi.", null=True, verbose_name='Yakunlangan sana')),
                ('contest', models.ForeignKey(help_text="Ushbu ro'yxatdan o'tish qaysi tanlovga tegishli ekanligi.", on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest', verbose_name='Tegishli musobaqa')),
                ('owner', models.ForeignKey(help_text='Ushbu yozuvni tizimga kiritgan/nazorat qiluvchi staff foydalanuvchi.', on_delete=django.db.models.deletion.CASCADE, related_name='contests_registration', to=settings.AUTH_USER_MODEL, verbose_name='Qayd etgan admin')),
                ('user', models.ForeignKey(help_text="Tanlovga ro'yxatdan o'tgan foydalanuvchi (Telegram bot foydalanuvchisi).", on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to='baseuser.baseuser', verbose_name='Ishtirokchi')),
            ],
            options={
                'verbose_name': "🪪 Ro'yxatdan o'tish",
                'verbose_name_plural': "👥 Ro'yxatdan o'tganlar",
                'ordering': ['rank', '-total_xp_earned'],
            },
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['status', 'start_time'], name='contests_co_status_72dc20_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['type'], name='contests_co_type_5591ba_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['slug'], name='contests_co_slug_fe75b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestprize',
            unique_together={('contest', 'rank_target')},
        ),
        migrations.AddIndex(
            model_name='contestregistration',
            index=models.Index(fields=['contest', 'rank'], name='contests_co_contest_6e2f16_idx'),
        ),
        migrations.AddIndex(
            model_name='contestregistration',
            index=models.Index(fields=['contest', '-total_xp_earned'], name='contests_co_contest_9da894_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestregistration',
            unique_together={('user', 'contest')},
        ),
    ]
