# Generated by Django 5.2.15 on 2026-08-06 07:21

import django.db.models.deletion
import mdeditor.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('centers', '0001_initial'),
        ('problems', '0001_initial'),
        ('quizs', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text="Foydalanuvchilarga ko'rinadigan musobaqa nomi. Masalan: Python Weekly Contest #1.", max_length=255, verbose_name='Musobaqa nomi')),
                ('slug', models.SlugField(blank=True, help_text="Musobaqa sahifasi uchun yagona URL nomi. Bo'sh qoldirilsa avtomatik yaratiladi.", max_length=255, unique=True, verbose_name='URL manzili (Slug)')),
                ('description', mdeditor.fields.MDTextField(blank=True, help_text="Musobaqa haqida batafsil ma'lumot, qoidalar va izohlar.", verbose_name='Musobaqa tavsifi')),
                ('visibility', models.CharField(choices=[('public', 'Ochiq'), ('private', 'Yopiq')], db_index=True, default='public', help_text="Musobaqa hammaga ochiq yoki faqat maxsus kalit orqali kiriladigan bo'lishi mumkin.", max_length=10, verbose_name="Ko'rinish turi")),
                ('contest_type', models.CharField(choices=[('icpc', 'ICPC (vaqt jarimasi)'), ('dynamic', 'Dinamik ball (Codeforces uslubi)'), ('simple', "Oddiy (faqat to'g'ri/noto'g'ri)")], default='icpc', help_text='Ball va jarima qanday hisoblanishini belgilaydi.', max_length=10, verbose_name='Baholash turi')),
                ('format', models.CharField(choices=[('coding', 'Faqat dasturlash masalalari'), ('quiz', 'Faqat variantli savollar'), ('mixed', 'Aralash (kod + variant)')], db_index=True, default='coding', help_text="Frontend qanday interfeys ko'rsatishini aniqlaydi: kod muharriri, variant (A/B/C/D) tugmalari yoki ikkalasi. Admin qo'lda tanlaydi yoki 'refresh_format()' orqali contest_problems asosida avtomatik yangilanadi.", max_length=10, verbose_name='Musobaqa formati')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tish muddati")),
                ('duration_minutes', models.PositiveIntegerField(help_text='Musobaqaning umumiy davomiyligi daqiqalarda.', verbose_name='Davomiyligi (daqiqa)')),
                ('allow_practice', models.BooleanField(default=True, verbose_name='Mashq rejimiga ruxsat')),
                ('penalty_minutes_per_wrong', models.PositiveIntegerField(default=20, help_text="ICPC turidagi musobaqalar uchun har xato urinishga qo'shiladigan jarima.", verbose_name='Xato urinish jarimasi (daqiqa)')),
                ('access_key', models.CharField(blank=True, help_text="Faqat yopiq musobaqalar uchun. Bo'sh qoldirilsa musobaqa ochiq bo'ladi.", max_length=100, null=True, verbose_name='Kirish kaliti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan sana')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='centers.center', verbose_name='Markaz')),
                ('intro_video', models.ForeignKey(blank=True, help_text="Musobaqa boshlanishidan oldin ishtirokchilarga ko'rsatiladigan qoida, tushuntirish yoki yo'riqnoma videosi. Ixtiyoriy maydon.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='video.video', verbose_name='Tanishtiruv videosi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL, verbose_name='Tashkilotchi')),
            ],
            options={
                'verbose_name': '🏆 Musobaqa',
                'verbose_name_plural': '🏆 Musobaqalar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='A, B, C ... yoki 1, 2, 3 ...', max_length=2, verbose_name='Harf/Raqam')),
                ('order_index', models.PositiveSmallIntegerField(verbose_name='Tartib raqami')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Maksimal ball')),
                ('is_scoring_dynamic', models.BooleanField(default=False, help_text='Yoqilsa, ball vaqt/urinish soniga qarab kamayib boradi.', verbose_name='Dinamik ball')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contest_links', to='problems.problem', verbose_name='Dasturlash masalasi')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contest_links', to='quizs.question', verbose_name='Test savoli')),
            ],
            options={
                'verbose_name': '🔗 Contest — Masala/Savol',
                'verbose_name_plural': '🔗 Contest — Masalalar/Savollar',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', through='contests.ContestProblem', to='problems.problem', verbose_name='Masalalar'),
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Har bir seans uchun noyob UUID identifikator.', primary_key=True, serialize=False, verbose_name='Identifikator')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', "Muddati o'tgan"), ('disqualified', 'Diskvalifikatsiya qilingan')], db_index=True, default='in_progress', help_text="Seans hozirgi holati: jarayonda, yakunlangan, muddati o'tgan yoki diskvalifikatsiya qilingan.", max_length=20, verbose_name='Holati')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('unanswered_count', models.PositiveIntegerField(default=0, verbose_name='Javobsiz qoldirilgan savollar soni')),
                ('score', models.FloatField(default=0.0, help_text='Jarima koeffitsiyenti hisobga olingan sof ball.', verbose_name='Yakuniy ball')),
                ('penalty_minutes', models.PositiveIntegerField(default=0, help_text='ICPC uslubidagi vaqt jarimasi — teng ballda tartiblash uchun ishlatiladi.', verbose_name='Jarima (daqiqa)')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('total_xp_earned', models.PositiveIntegerField(db_index=True, default=0, help_text="Foydalanuvchi ushbu testdan ishlagan toza XP ballari. Reyting shu maydon bo'yicha tuziladi.", verbose_name='Ushbu musobaqa jami XP balli')),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, help_text="Tanlov yakunlangach hisoblangan, ushbu ishtirokchining umumiy reytingdagi o'rni (1 — birinchi o'rin).", null=True, verbose_name="Musobaqadagi o'rni")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Ishtirokchi testni boshlagan paytdagi IP manzili. Firibgarlikni aniqlash uchun foydali.', null=True, verbose_name='IP manzil')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan sana')),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text="Test yakunlangan yoki muddati tugagan payt. Avtomat to'ldiriladi.", null=True, verbose_name='Yakunlangan sana')),
                ('contest', models.ForeignKey(help_text="Ushbu ro'yxatdan o'tish qaysi tanlovga tegishli ekanligi.", on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest', verbose_name='Tegishli musobaqa')),
                ('owner', models.ForeignKey(blank=True, help_text='Ushbu yozuvni tizimga kiritgan/nazorat qiluvchi staff foydalanuvchi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests_registration', to=settings.AUTH_USER_MODEL, verbose_name='Qayd etgan admin')),
                ('user', models.ForeignKey(help_text="Tanlovga ro'yxatdan o'tgan foydalanuvchi (Telegram bot foydalanuvchisi).", on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to='baseuser.baseuser', verbose_name='Ishtirokchi')),
            ],
            options={
                'verbose_name': "🪪 Ro'yxatdan o'tish",
                'verbose_name_plural': "👥 Ro'yxatdan o'tganlar",
                'ordering': ['rank', '-score', 'penalty_minutes'],
            },
        ),
        migrations.CreateModel(
            name='ContestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt')),
                ('choice', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — javobsiz qoldirilgan.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_answers', to='quizs.choice', verbose_name='Tanlangan variant')),
                ('contest_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='contests.contestproblem', verbose_name='Contest bandi')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='contests.contestregistration', verbose_name="Ro'yxatdan o'tish")),
            ],
            options={
                'verbose_name': '📮 Contest javobi (Quiz)',
                'verbose_name_plural': '📮 Contest javoblari (Quiz)',
            },
        ),
        migrations.CreateModel(
            name='CheatFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('tab_switch', 'Tab almashtirildi'), ('multiple_ip', 'Bir nechta IP manzil'), ('copy_paste', "Ko'p marta copy-paste"), ('time_anomaly', 'Vaqt anomaliyasi'), ('similar_code', "Boshqa foydalanuvchi kodi bilan o'xshashlik"), ('manual', "Qo'lda belgilangan")], max_length=20, verbose_name='Sabab')),
                ('detail', models.TextField(blank=True, verbose_name='Tafsilot')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Aniqlangan vaqt')),
                ('reviewed', models.BooleanField(default=False, verbose_name="Ko'rib chiqilgan")),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cheat_flags', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan admin")),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_flags', to='contests.contestregistration', verbose_name="Ro'yxatdan o'tish")),
            ],
            options={
                'verbose_name': '🚩 Shubhali harakat',
                'verbose_name_plural': '🚩 Shubhali harakatlar',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Noutbuk, Sertifikat, Oltin medal.', max_length=200, verbose_name='Mukofot nomi')),
                ('rank_target', models.PositiveSmallIntegerField(default=1, help_text="Ushbu mukofot nechinchi o'rin uchun mo'ljallanganini bildiradi (masalan: 1, 2, 3).", verbose_name="O'rin (reyting)")),
                ('description', mdeditor.fields.MDTextField(blank=True, help_text="Mukofot haqida batafsil ma'lumot, shartlar yoki izohlar.", null=True, verbose_name="Qo'shimcha tavsif")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('contest', models.ForeignKey(help_text="Mukofot tegishli bo'lgan tanlov.", on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='contests.contest', verbose_name='Musobaqa')),
                ('owner', models.ForeignKey(help_text='Mukofotni tizimga kiritgan staff foydalanuvchi.', on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan admin")),
            ],
            options={
                'verbose_name': '🎁 Mukofot',
                'verbose_name_plural': '🎁 Mukofotlar',
                'ordering': ['rank_target'],
                'unique_together': {('contest', 'rank_target')},
            },
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('problem__isnull', False), ('question__isnull', True)), models.Q(('problem__isnull', True), ('question__isnull', False)), _connector='OR'), name='contest_problem_belongs_to_problem_xor_question'),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('problem__isnull', False)), fields=('contest', 'problem'), name='unique_problem_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('contest', 'question'), name='unique_question_per_contest'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['visibility'], name='contests_co_visibil_506182_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['start_time'], name='contests_co_start_t_2c1630_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['end_time'], name='contests_co_end_tim_806786_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['slug'], name='contests_co_slug_fe75b1_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['format'], name='contests_co_format_89e0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='contestregistration',
            index=models.Index(fields=['contest', 'rank'], name='contests_co_contest_6e2f16_idx'),
        ),
        migrations.AddIndex(
            model_name='contestregistration',
            index=models.Index(fields=['contest', '-total_xp_earned'], name='contests_co_contest_9da894_idx'),
        ),
        migrations.AddIndex(
            model_name='contestregistration',
            index=models.Index(fields=['contest', '-score', 'penalty_minutes'], name='contests_co_contest_3b5680_idx'),
        ),
        migrations.AddConstraint(
            model_name='contestregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('xp_awarded__gt', 0)), fields=('user', 'contest'), name='unique_xp_award_per_user_contest'),
        ),
        migrations.AlterUniqueTogether(
            name='contestregistration',
            unique_together={('user', 'contest')},
        ),
        migrations.AddIndex(
            model_name='contestanswer',
            index=models.Index(fields=['registration', 'contest_problem'], name='contests_co_registr_92c048_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contestanswer',
            unique_together={('registration', 'contest_problem')},
        ),
    ]
