# Generated by Django 5.2.15 on 2026-07-12 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestregistration',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='contestregistration',
            name='contests_co_contest_6e2f16_idx',
        ),
        migrations.RemoveIndex(
            model_name='contestregistration',
            name='contests_co_contest_9da894_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contestregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contestregistration',
            name='xp_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestregistration',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Ushbu yozuvni tizimga kiritgan/nazorat qiluvchi staff foydalanuvchi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests_registration', to=settings.AUTH_USER_MODEL, verbose_name='Qayd etgan admin'),
        ),
        migrations.AddConstraint(
            model_name='contestregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('xp_awarded__gt', 0)), fields=('user', 'contest'), name='unique_xp_award_per_user_contest'),
        ),
    ]
