# Generated by Django 5.2.15 on 2026-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='letter',
            field=models.CharField(blank=True, editable=False, help_text='A, B, C ... AA, AB ...', max_length=3, null=True, verbose_name='Harf/Raqam'),
        ),
    ]
