# Generated by Django 5.2.15 on 2026-06-28 02:02

import django.db.models.deletion
import uuid
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, help_text='Kompyuteringizdan darslikning asl video faylini yuklang.', null=True, upload_to='movies/videos/', verbose_name='Asl video fayli (MP4)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Videoga tegishli rasm (poster) yuklang. Avtomat 16:9 qilib kesiladi va siqiladi.', null=True, upload_to='movies/thumbnails/', validators=[video.models.validate_image_extension], verbose_name='Video muqovasi (Rasm)')),
                ('hls_url', models.URLField(blank=True, null=True, verbose_name='HLS (m3u8) oqim manzili')),
                ('duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Video davomiyligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🎬 Video',
                'verbose_name_plural': '🎥 Videolar',
            },
        ),
    ]
