# Generated by Django 6.0.2 on 2026-06-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video uchun qisqa va tushunarli nom', max_length=250, verbose_name='Video sarlavhasi')),
                ('slug', models.SlugField(blank=True, help_text='URL uchun avtomatik yaratiladigan qism', max_length=300, unique=True)),
                ('duration', models.CharField(blank=True, help_text='Davomiyligi (masalan: 12:45)', max_length=50, null=True)),
                ('description', models.TextField(help_text="Video haqida batafsil ma'lumot", verbose_name='Tavsif')),
                ('image', models.ImageField(help_text="Video ro'yxatda ko'ringanda chiqadigan rasm", upload_to='movies/posters/', verbose_name='Asosiy rasm')),
                ('thumbnail', models.URLField(blank=True, help_text='Tashqi manbadagi kichik rasm (URL)', null=True)),
                ('backdrop_image', models.ImageField(blank=True, help_text="Video pleyer orqasida ko'rinadigan katta rasm", null=True, upload_to='movies/backdrops/', verbose_name='Fon rasmi')),
                ('backdrop', models.URLField(blank=True, help_text='Tashqi manbadagi fon rasmi (URL)', null=True)),
                ('video', models.FileField(blank=True, help_text='Asl video faylini yuklang (mp4)', null=True, upload_to='movies/videos/', verbose_name='Video fayli')),
                ('hls_url', models.URLField(blank=True, help_text='Video oqimi (streaming) uchun link', null=True, verbose_name='HLS (m3u8) manzili')),
                ('mp4_url', models.URLField(blank=True, help_text="Video yuklab olish uchun to'g'ridan-to'g'ri link", null=True, verbose_name='MP4 manzili')),
                ('problem', models.ForeignKey(blank=True, help_text="Agar video konkret bir masalaga tegishli bo'lsa tanlang", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_videos', to='problems.problem')),
            ],
            options={
                'verbose_name': '🎬 Video',
                'verbose_name_plural': '🎥 Videolar',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['slug'], name='video_video_slug_89c582_idx'), models.Index(fields=['id'], name='video_video_id_761ed0_idx')],
            },
        ),
    ]
