# Generated by Django 5.2.15 on 2026-06-15 13:21

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Video darslik yoki yechim tahlili uchun qisqa va tushunarli nom kiriting (Masalan: 'A+B masalasi tahlili').", max_length=250, verbose_name='Video sarlavhasi')),
                ('slug', models.SlugField(blank=True, help_text="Brauzer havolasi (URL) uchun sarlavhadan avtomatik generatsiya qilinadigan qism. Qo'lda yozish shart emas.", max_length=300, unique=True, verbose_name='URL sarlavha (Slug)')),
                ('duration', models.CharField(blank=True, help_text="Video darslikning davomiyligi (Masalan: 12:45). Video fayli yuklanganidan so'ng, Celery buni fonda avtomatik to'ldiradi.", max_length=50, null=True, verbose_name='Davomiyligi')),
                ('description', mdeditor.fields.MDTextField(help_text="Video darslik mazmuni haqida batafsil ma'lumot. Markdown belgilari yordamida formula va kodlarni chiroyli yozishingiz mumkin.", verbose_name='Batafsil tavsif')),
                ('image', models.ImageField(blank=True, help_text='Videoning vertikal muqovasi (poster). Kompyuteringizdan rasm faylini yuklang (MinIO/S3 bulutli omboriga saqlanadi).', null=True, upload_to='movies/posters/', verbose_name='Asosiy rasm (Poster fayl)')),
                ('thumbnail', models.URLField(blank=True, help_text="Videoning kichik muqovasi uchun tayyor internet havolasi (URL). Video yuklangandan keyin, Celery birinchi sekundlardan qirqib olib avtomat to'ldiradi.", null=True, verbose_name='Tashqi rasm (Poster URL)')),
                ('backdrop_image', models.ImageField(blank=True, help_text='Video pleyer orqasida yoki dars sahifasining yuqori qismida fon (background) sifatida turadigan keng formatli (16:9) katta rasm fayli.', null=True, upload_to='movies/backdrops/', verbose_name='Katta fon rasmi (Backdrop fayl)')),
                ('backdrop', models.URLField(blank=True, help_text='Video sahifasining orqa foni uchun tayyor internet havolasini (URL) kiriting. Bu serverda joy tejashga yordam beradi.', null=True, verbose_name='Tashqi fon rasmi (Backdrop URL)')),
                ('video', models.FileField(blank=True, help_text="Kompyuteringizdan darslikning asl video faylini (MP4 formatida) yuklang. Tizim uni fonda avtomat HLS formatiga o'giradi.", null=True, upload_to='movies/videos/', verbose_name='Asl video fayli (MP4)')),
                ('hls_url', models.URLField(blank=True, help_text='Video darslikning onlayn tezkor oqimli (streaming) uzatish linki. Video yuklangandan keyin, Celery buni avtomat yaratadi.', null=True, verbose_name='HLS (m3u8) oqim manzili')),
                ('mp4_url', models.URLField(blank=True, help_text="Videoni foydalanuvchilar yuklab olishi uchun to'g'ridan-to'g'ri link. Celery tomonidan avtomatik to'ldiriladi.", null=True, verbose_name="MP4 to'g'ridan-to'g'ri manzili")),
            ],
            options={
                'verbose_name': '🎬 Video',
                'verbose_name_plural': '🎥 Videolar',
                'ordering': ['-title'],
                'indexes': [models.Index(fields=['slug'], name='video_video_slug_89c582_idx')],
            },
        ),
    ]
