# Generated by Django 5.2.15 on 2026-08-28 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaschCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('algorithm_version', models.CharField(default='rasch-mml-v3', max_length=50)),
                ('response_policy', models.CharField(default='first_attempt_only', max_length=30)),
                ('sample_size', models.PositiveIntegerField(default=0, help_text='Noyob shaxslar (userlar) soni.')),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('mean_beta', models.FloatField(default=0.0)),
                ('std_beta', models.FloatField(default=0.0)),
                ('min_beta', models.FloatField(default=0.0)),
                ('max_beta', models.FloatField(default=0.0)),
                ('converged', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('data_cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Hisoblanmoqda'), ('completed', "Yakunlandi (ko'rib chiqilmoqda)"), ('failed', 'Xatolik'), ('rejected', 'Rad etildi'), ('active', 'Faol'), ('retired', 'Almashtirildi')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Rasch kalibratsiyasi',
                'verbose_name_plural': 'Rasch kalibratsiyalari',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('rasch_min_persons', models.PositiveIntegerField(default=100, help_text="Kalibratsiya statistik jihatdan barqaror bo'lishi uchun kamida shuncha ishtirokchi kerak.", verbose_name='Kalibratsiya uchun minimal ishtirokchilar')),
                ('rasch_recalibration_response_threshold', models.PositiveIntegerField(default=500, verbose_name='Qayta kalibratsiya chegarasi (yangi javoblar)')),
                ('rasch_prior_variance', models.FloatField(default=1.0, help_text='N(0, sigma²) prior. Standart = 1.0.', verbose_name='MAP prior variance')),
                ('rasch_theta_min', models.FloatField(default=-6.0, verbose_name='θ minimum')),
                ('rasch_theta_max', models.FloatField(default=6.0, verbose_name='θ maximum')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Javob izohi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('dif_group', models.CharField(blank=True, help_text='Kelajakda Differential Item Functioning tahlili uchun.', max_length=50, null=True, verbose_name='DIF guruhi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quizs.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': '❓ Savol',
                'verbose_name_plural': '❔ Savollar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizs.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': '🔘 Javob varianti',
                'verbose_name_plural': '✅ Javob variantlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RaschItemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta', models.FloatField(default=0.0, verbose_name='β qiyinchilik')),
                ('beta_se', models.FloatField(default=999.0, verbose_name='β SE')),
                ('infit', models.FloatField(blank=True, null=True)),
                ('outfit', models.FloatField(blank=True, null=True)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('is_calibrated', models.BooleanField(default=False)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('is_extreme', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_parameters', to='quizs.raschcalibration')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasch_parameters', to='quizs.question')),
            ],
            options={
                'verbose_name': 'Rasch item parametri',
                'verbose_name_plural': 'Rasch item parametrlari',
            },
        ),
        migrations.CreateModel(
            name='ScoringPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100, verbose_name='Siyosat nomi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('theta_low', models.FloatField(default=-4.0, verbose_name='θ → 0 ball')),
                ('theta_high', models.FloatField(default=4.0, verbose_name='θ → 100 ball')),
                ('grade_a_plus_min', models.FloatField(default=70.0, verbose_name='A+ minimum')),
                ('grade_a_min', models.FloatField(default=65.0, verbose_name='A minimum')),
                ('grade_b_plus_min', models.FloatField(default=60.0, verbose_name='B+ minimum')),
                ('grade_b_min', models.FloatField(default=55.0, verbose_name='B minimum')),
                ('grade_c_plus_min', models.FloatField(default=50.0, verbose_name='C+ minimum')),
                ('grade_c_min', models.FloatField(default=46.0, verbose_name='C minimum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_policies', to='quizs.subject')),
            ],
            options={
                'verbose_name': 'Baholash siyosati',
                'verbose_name_plural': 'Baholash siyosatlari',
            },
        ),
        migrations.AddField(
            model_name='raschcalibration',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasch_calibrations', to='quizs.subject'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test sharti')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa)')),
                ('random_questions_count', models.PositiveIntegerField(default=0, help_text="0 = barcha savollar ko'rsatiladi.", verbose_name='Tasodifiy savollar soni')),
                ('rasch_theta_pass_threshold', models.FloatField(default=0.0, verbose_name="O'tish chegarasi (θ, logit)")),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='Maksimal urinishlar soni')),
                ('access_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kirish kodi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Test narxi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirmadagi narx')),
                ('max_lifelines', models.PositiveIntegerField(default=3, verbose_name='Maksimal Yordam soni')),
                ('reveal_correct_answers', models.BooleanField(default=False, help_text="Savollar banki qayta ishlatilsa, O'CHIRIQ holda qoldiring.", verbose_name="To'g'ri javoblarni ochish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='quizs.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': '📋 Test',
                'verbose_name_plural': '📋 Testlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov summasi")),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quizs.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🛒 Sotib olingan test',
                'verbose_name_plural': '🛒 Sotib olingan testlar',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_usages', to='quizs.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='quizs.test')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tests', through='quizs.TestQuestion', to='quizs.question'),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Seans ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', "Muddati o'tgan")], db_index=True, default='in_progress', max_length=20)),
                ('rasch_theta', models.FloatField(blank=True, null=True, verbose_name='Qobiliyat (θ, logit)')),
                ('rasch_se', models.FloatField(blank=True, null=True, verbose_name='Standart xatolik (SE)')),
                ('rasch_converged', models.BooleanField(default=False, verbose_name='θ baholash yaqinlashdimi')),
                ('person_infit', models.FloatField(blank=True, null=True)),
                ('person_outfit', models.FloatField(blank=True, null=True)),
                ('scaled_score', models.FloatField(blank=True, null=True, verbose_name='0-100 shkala ball')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Daraja')),
                ('grade_description', models.CharField(blank=True, max_length=50, verbose_name='Daraja tavsifi')),
                ('is_provisional', models.BooleanField(default=False, help_text="True bo'lsa — savollarning muhim qismi hali kalibrlanmagan.", verbose_name='Vaqtinchalik natija')),
                ('uncalibrated_question_count', models.PositiveIntegerField(default=0)),
                ('raw_percentage', models.FloatField(default=0.0, verbose_name='Oddiy foiz (%)')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('unanswered_count', models.PositiveIntegerField(default=0)),
                ('lifelines_used', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rasch_calibration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='quizs.raschcalibration', verbose_name='Ishlatilgan kalibratsiya')),
                ('scoring_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='quizs.scoringpolicy', verbose_name='Ishlatilgan siyosat')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizs.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '⏱ Test Seansi',
                'verbose_name_plural': '⏱ Test Seanslari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_usages', to='quizs.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='quizs.testsession')),
            ],
            options={
                'verbose_name': 'Seans savoli',
                'verbose_name_plural': 'Seans savollari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(blank=True, help_text="Bo'sh = javobsiz qoldirilgan.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizs.choice', verbose_name='Tanlangan variant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='quizs.question', verbose_name='Savol')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizs.testsession', verbose_name='Test seansi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '🎯 Foydalanuvchi Javobi',
                'verbose_name_plural': '🎯 Foydalanuvchi Javoblari',
            },
        ),
        migrations.CreateModel(
            name='UserSubjectAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theta', models.FloatField(verbose_name='Qobiliyat (θ)')),
                ('theta_se', models.FloatField(default=999.0, verbose_name='Standart xatolik')),
                ('person_infit', models.FloatField(blank=True, null=True)),
                ('person_outfit', models.FloatField(blank=True, null=True)),
                ('calibration_version', models.PositiveIntegerField()),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_abilities', to='quizs.raschcalibration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_abilities', to='quizs.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_abilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi fan darajasi',
                'verbose_name_plural': 'Foydalanuvchi fan darajalari',
            },
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_choice_per_question'),
        ),
        migrations.AddIndex(
            model_name='raschitemparameter',
            index=models.Index(fields=['question'], name='quizs_rasch_questio_795a04_idx'),
        ),
        migrations.AddConstraint(
            model_name='raschitemparameter',
            constraint=models.UniqueConstraint(fields=('calibration', 'question'), name='unique_item_per_calibration'),
        ),
        migrations.AddConstraint(
            model_name='scoringpolicy',
            constraint=models.UniqueConstraint(fields=('subject', 'version'), name='unique_policy_version_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='scoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subject',), name='unique_active_policy_per_subject'),
        ),
        migrations.AddIndex(
            model_name='raschcalibration',
            index=models.Index(fields=['subject', 'status'], name='quizs_rasch_subject_bf6f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='raschcalibration',
            index=models.Index(fields=['subject', 'is_active'], name='quizs_rasch_subject_87db0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='raschcalibration',
            constraint=models.UniqueConstraint(fields=('subject', 'version'), name='unique_rasch_calibration_version'),
        ),
        migrations.AddConstraint(
            model_name='raschcalibration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subject',), name='unique_active_calibration_per_subject'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'dif_group'], name='quizs_quest_subject_0c2e85_idx'),
        ),
        migrations.AddIndex(
            model_name='testenrollment',
            index=models.Index(fields=['user', 'test'], name='quizs_teste_user_id_8a8b7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testenrollment',
            unique_together={('user', 'test')},
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='unique_question_per_test'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', 'test', 'status'], name='quizs_tests_user_id_ac8474_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['status', '-started_at'], name='quizs_tests_status_ba6b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['rasch_calibration'], name='quizs_tests_rasch_c_ce0bc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='testsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_question_per_session'),
        ),
        migrations.AddConstraint(
            model_name='userresponse',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_response_per_session_question'),
        ),
        migrations.AddIndex(
            model_name='usersubjectability',
            index=models.Index(fields=['user', 'subject'], name='quizs_users_user_id_a13001_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubjectability',
            index=models.Index(fields=['subject', '-theta'], name='quizs_users_subject_76c2a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubjectability',
            constraint=models.UniqueConstraint(fields=('user', 'subject'), name='unique_user_subject_ability'),
        ),
    ]
