# Generated by Django 5.2.15 on 2026-08-06 07:21

import django.core.validators
import django.db.models.deletion
import mdeditor.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('centers', '0001_initial'),
        ('courses', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', help_text='Savolning murakkablik darajasi. Darajaga qarab avtomatik XP ballari belgilanadi.', max_length=10, verbose_name='Qiyinchilik darajasi')),
                ('text', mdeditor.fields.MDTextField(help_text="Markdown formatida savol matnini va shartini to'liq yozing.", verbose_name='Savol matni')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Savollarning test sahifasida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami')),
                ('xp', models.PositiveIntegerField(default=5, help_text="Ushbu savol to'g'ri topilganda foydalanuvchiga beriladigan ball miqdori (5 dan 20 gacha).", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='XP mukofoti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('explanation_video', models.ForeignKey(blank=True, help_text="Talaba xato qilganda javobni tushunishi va tahlilini ko'rishi uchun biriktiriladigan video darslik.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_explanations', to='video.video', verbose_name='Savol video tahlili')),
                ('lesson', models.ForeignKey(blank=True, help_text="Agar ushbu savol muayyan dars ichidagi amaliyot uchun bo'lsa, darsni tanlang.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='courses.lesson', verbose_name='Darslik')),
                ('owner', models.ForeignKey(help_text="Ushbu savolni tizimga qo'shgan mas'ul xodim yoki o'qituvchi.", on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name="Yaratuvchi o'qituvchi")),
            ],
            options={
                'verbose_name': '❓ Savol',
                'verbose_name_plural': '❔ Savollar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', mdeditor.fields.MDTextField(help_text='Markdown formatida javob variantining matnini kiriting.', verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(db_index=True, default=False, help_text="Agar ushbu variant savolning to'g'ri javobi bo'lsa, belgilang.", verbose_name="To'g'ri javob")),
                ('explanation', mdeditor.fields.MDTextField(blank=True, help_text="Talaba ushbu variantni tanlaganidan keyin (yoki test yakunida) nega bu javob to'g'ri/noto'g'ri ekanligini tushuntiruvchi matn.", null=True, verbose_name='Javob izohi / Tushuntirish')),
                ('order', models.PositiveIntegerField(default=0, help_text='Javob variantlarining foydalanuvchiga qaysi ketma-ketlikda chiqishini belgilovchi raqam.', verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('owner', models.ForeignKey(help_text="Ushbu variantni tizimga qo'shgan mas'ul xodim yoki o'qituvchi.", on_delete=django.db.models.deletion.CASCADE, related_name='created_choices', to=settings.AUTH_USER_MODEL, verbose_name="Yaratuvchi o'qituvchi")),
                ('question', models.ForeignKey(help_text='Ushbu variant qaysi savolga tegishli ekanligini belgilang.', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizs.question', verbose_name='Tegishli savol')),
            ],
            options={
                'verbose_name': '🔘 Javob varianti',
                'verbose_name_plural': '✅ Javob variantlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Test yoki imtihon majmuasining to'liq sarlavhasi.", max_length=255, verbose_name='Test nomi')),
                ('slug', models.SlugField(help_text="URL manzillari uchun avtomatik hosil bo'luvchi qisqa nom.", max_length=255, unique=True, verbose_name='Slug')),
                ('description', mdeditor.fields.MDTextField(help_text="Markdown formatida masalaning to'liq shartini yozing.", null=True, verbose_name='test sharti (Matn)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Testni yechish uchun foydalanuvchiga beriladigan umumiy vaqt (daqiqa hisobida).', verbose_name='Davomiyligi (daqiqa)')),
                ('question_count', models.PositiveIntegerField(default=0, help_text="Ushbu test tarkibiga qo'shilgan jami umumiy savollar soni (avtomatik yoki qo'lda yangilanadi).", verbose_name='Bazasidagi jami savollar soni')),
                ('random_questions_count', models.PositiveIntegerField(default=0, help_text="0 = barcha savollar ko'rsatiladi. Agar masalan bazada 100 ta savol bo'lsa va bu yerga 20 yozilsa, foydalanuvchiga random 20 ta savol ajratib beriladi.", verbose_name="Foydalanuvchiga ko'rsatiladigan tasodifiy savollar soni")),
                ('min_pass_percentage', models.PositiveIntegerField(default=60, help_text="Testdan muvaffaqiyatli o'tish uchun talaba to'plashi kerak bo'lgan eng kam foiz ko'rsatkichi (0-100).", validators=[django.core.validators.MaxValueValidator(100)], verbose_name="O'tish foizi")),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text="Foydalanuvchi ushbu testni ko'pi bilan necha marta topshira olishi. 0 = cheksiz urinishlar.", verbose_name='Maksimal urinishlar soni')),
                ('access_code', models.CharField(blank=True, help_text="Testni boshlash uchun maxsus parol (bo'sh qoldirilsa = hamma uchun ochiq).", max_length=50, null=True, verbose_name='Kirish kodi')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Test talabalarga ko'rinishi yoki vaqtincha yashirib qo'yilishi uchun boshqaruv belgisi.", verbose_name='Faol')),
                ('start_time', models.DateTimeField(help_text='Test tizimda faollashadigan va talabalar kirishi boshlanadigan aniq sana va vaqt.', verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(help_text='Test butunlay yopiladigan muddat. Ushbu vaqtdan keyin talabalar testga kira olishmaydi.', verbose_name='Tugash vaqti')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text="Agar test pullik bo'lsa, uning asosiy qiymati (bepul bo'lsa 0.00 qoldiring).", max_digits=10, verbose_name='Test narxi')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Aksiya va chegirmalar vaqtida amal qiladigan arzonlashtirilgan narx.', max_digits=10, null=True, verbose_name='Chegirmadagi narx')),
                ('penalty_coefficient', models.FloatField(default=0.33, help_text="Noto'g'ri javoblar uchun jarima koeffitsiyenti. Masalan: 0.33 yozilsa, 3 ta xato javob 1 ta to'g'ri javob ballini olib ketadi.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Jarima koeffitsiyenti (K)')),
                ('max_lifelines', models.PositiveIntegerField(default=3, help_text="Talaba test davomida foydalanishi mumkin bo'lgan yordam vositalari (Lifeline) soni.", verbose_name='Maksimal Reler (Lifeline) soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='centers.center', verbose_name='Markaz')),
                ('intro_video', models.ForeignKey(blank=True, help_text="Testni boshlashdan oldin ko'rsatiladigan yo'riqnoma yoki tushuntirish videosi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_video', to='video.video', verbose_name='Kirish yoki qoidalar videosi')),
                ('modul', models.ForeignKey(blank=True, help_text="Agar bo'sh qolsa, bu mustaqil umumiy imtihon testi hisoblanadi. Aks holda, bu bob (modul) yakunidagi test.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='courses.modul', verbose_name='Bob (Modul)')),
                ('owner', models.ForeignKey(help_text="Ushbu test majmuasini yaratgan va unga egalik qiluvchi o'qituvchi/admin.", on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name="Yaratuvchi o'qituvchi")),
            ],
            options={
                'verbose_name': '📋 Test',
                'verbose_name_plural': '📋 Testlar',
                'ordering': ['-id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, help_text='Agar ushbu savol biror imtihon yoki modul yakuniy testi tarkibiga kirsa, testni tanlang.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quizs.test', verbose_name='Test (Imtihon)'),
        ),
        migrations.CreateModel(
            name='TestEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quizs.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_enrollments', to='baseuser.baseuser')),
            ],
            options={
                'verbose_name': '🛒 Sotib olingan test',
                'verbose_name_plural': '🛒 Sotib olingan testlar',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Har bir test topshirish seansi uchun unikal UUID identifikator.', primary_key=True, serialize=False, verbose_name='Seans ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', "Muddati o'tgan")], db_index=True, default='in_progress', help_text="Test jarayonining joriy holati: jarayonda, yakunlangan yoki vaqti o'tib ketgan (muddati o'tgan).", max_length=20, verbose_name='Seans holati')),
                ('score', models.FloatField(default=0.0, help_text="S = Sum(C*P) - Sum(W*P*K) formulasi bo'yicha jarima koeffitsiyentini hisobga olgan holda aniqlangan sof ball.", verbose_name='Yakuniy akademik ball (S)')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text="Talaba tomonidan ushbu seansda to'g'ri belgilangan savollarning umumiy miqdori.", verbose_name="To'g'ri javoblar soni")),
                ('wrong_count', models.PositiveIntegerField(default=0, help_text="Talaba xato belgilagan yoki noto'g'ri topshirgan savollar soni.", verbose_name="Noto'g'ri javoblar soni")),
                ('unanswered_count', models.PositiveIntegerField(default=0, help_text="Talaba tomonidan belgilamasdan o'tkazib yuborilgan yoki vaqt yetmay umuman ochilmagan savollar soni.", verbose_name='Javobsiz qoldirilganlar soni')),
                ('total_xp_earned', models.PositiveIntegerField(db_index=True, default=0, help_text="Ushbu urinish natijasida foydalanuvchining global profiliga qo'shish uchun hisoblangan butun sonli mukofot balli.", verbose_name='Yutilgan XP ball')),
                ('lifelines_used', models.PositiveIntegerField(default=0, help_text="Ushbu seansda foydalanuvchi hozirgacha ishlatgan lifeline'lar soni (faqat serverda hisoblanadi, frontend hisoblagichiga ishonilmaydi).", verbose_name='Ishlatilgan Reler (Lifeline) soni')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Foydalanuvchi testni yechishni boshlagan aniq sana va vaqt.', verbose_name='Boshlangan vaqti')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Test yakunlangan yoki vaqt tugashi sababli tizim tomonidan yopilgan aniq vaqt.', null=True, verbose_name='Yakunlangan vaqti')),
                ('test', models.ForeignKey(help_text='Topshirilayotgan test yoki imtihon majmuasi.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizs.test', verbose_name='Test (Imtihon)')),
                ('user', models.ForeignKey(help_text="Testni topshirayotgan (tizimda faol bo'lgan) talaba.", on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '⏱ Test Seansi',
                'verbose_name_plural': '⏱ Test Seanslari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Talaba joriy savolga javob tugmasini bosgan aniq vaqt.', verbose_name='Javob berilgan vaqt')),
                ('choice', models.ForeignKey(blank=True, help_text="Talaba tomonidan belgilangan javob varianti (bo'sh qolsa = javobsiz qoldirilgan).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizs.choice', verbose_name='Tanlangan variant')),
                ('question', models.ForeignKey(help_text='Javob berilgan test yoki darslik savoli.', on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='quizs.question', verbose_name='Savol')),
                ('session', models.ForeignKey(blank=True, help_text='Ushbu javob aynan qaysi test topshirish urinishiga (seansiga) tegishli ekanligi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizs.testsession', verbose_name='Test seansi')),
                ('user', models.ForeignKey(help_text='Javob bergan talaba.', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '🎯 Foydalanuvchi Javobi',
                'verbose_name_plural': '🎯 Foydalanuvchi Javoblari',
            },
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_choice_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('test__isnull', True)), models.Q(('lesson__isnull', True), ('test__isnull', False)), _connector='OR'), name='question_belongs_to_lesson_xor_test'),
        ),
        migrations.AddIndex(
            model_name='testenrollment',
            index=models.Index(fields=['user', 'test'], name='quizs_teste_user_id_8a8b7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testenrollment',
            unique_together={('user', 'test')},
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', 'test', 'status'], name='quizs_tests_user_id_ac8474_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['status', '-started_at'], name='quizs_tests_status_ba6b6d_idx'),
        ),
    ]
