# Generated by Django 6.0.2 on 2026-06-12 16:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('courses', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=10)),
                ('xp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='problems.problem')),
            ],
            options={
                'verbose_name': '❓ Savol',
                'verbose_name_plural': '❔ Savollar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name="To'g'ri javob")),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Javob izohi / Tushuntirish')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizs.question')),
            ],
            options={
                'verbose_name': '🔘 Javob varianti',
                'verbose_name_plural': '✅ Javob variantlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqa)')),
                ('question_count', models.PositiveIntegerField(default=20, verbose_name='Savollar soni')),
                ('min_pass_percentage', models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100)], verbose_name="O'tish foizi")),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='Savollarni aralashtirish')),
                ('max_attempts', models.PositiveIntegerField(default=0, verbose_name='Maksimal urinishlar soni (0 = cheksiz)')),
                ('access_code', models.CharField(blank=True, max_length=50, null=True, verbose_name="Kirish kodi (bo'sh = ochiq)")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('deadline', models.DateTimeField(verbose_name='Testning tugash muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, help_text="Agar bo'sh qolsa, bu mustaqil umumiy imtihon testi hisoblanadi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='courses.lesson')),
            ],
            options={
                'verbose_name': '📝 Test',
                'verbose_name_plural': '📑 Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quizs.test'),
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shablon nomi')),
                ('html_content', models.TextField(help_text='Dinamik taglar: {{ full_name }}, {{ title }}, {{ date }}, {{ code }}, {{ qr_code_url }}', verbose_name='HTML Shabloni')),
                ('min_percentage', models.PositiveIntegerField(default=80, verbose_name="Minimal o'tish foizi")),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='courses.course')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='quizs.test')),
            ],
            options={
                'verbose_name': '📜 Sertifikat Shabloni',
                'verbose_name_plural': '📜 Sertifikat Shablonlari',
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', "Muddati o'tgan")], db_index=True, default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Foiz')),
                ('total_xp_earned', models.PositiveIntegerField(default=0, verbose_name="To'plangan XP")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Tugatgan vaqti')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to='problems.problem')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='quizs.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='baseuser.baseuser')),
            ],
            options={
                'verbose_name': '⏱️ Test Sessiyasi',
                'verbose_name_plural': '⏱️ Test Sessiyalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Jami to'plangan XP")),
                ('level', models.CharField(choices=[('beginner', 'Yangi boshlovchi'), ('bronze', 'Bronza'), ('silver', 'Kumush'), ('gold', 'Oltin'), ('pro', 'Professional')], default='beginner', max_length=20, verbose_name='Unvon (Daraja)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_profile', to='baseuser.baseuser')),
            ],
            options={
                'verbose_name': '🏅 Foydalanuvchi Reytingi',
                'verbose_name_plural': '🏅 Foydalanuvchilar Reytingi',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Sertifikat ID/Kodi')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/', verbose_name='QR Kod')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/', verbose_name='PDF Fayl')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqti')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_course_certificates', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='baseuser.baseuser')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizs.certificatetemplate')),
                ('test_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_test_certificate', to='quizs.testsession')),
            ],
            options={
                'verbose_name': '📜 Berilgan Sertifikat',
                'verbose_name_plural': '📜 Berilgan Sertifikatlar',
                'unique_together': {('user', 'course'), ('user', 'test_session')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizs.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizs.testsession')),
            ],
            options={
                'verbose_name': '👤 Talaba Javobi',
                'verbose_name_plural': '👤 Talaba Javoblari',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
