# Generated by Django 5.2.15 on 2026-06-15 13:37

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='explanation',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='Javob izohi / Tushuntirish'),
        ),
    ]
