# Generated by Django 5.2.15 on 2026-06-28 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='xp',
            field=models.PositiveIntegerField(default=5, help_text="Ushbu savol to'g'ri topilganda foydalanuvchiga beriladigan ball miqdori (5 dan 20 gacha).", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='XP mukofoti'),
        ),
    ]
