# Generated by Django 5.2.15 on 2026-06-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0002_alter_question_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Savollarning test sahifasida qaysi ketma-ketlikda chiqishini tartiblovchi raqam.', verbose_name='Tartib raqami'),
        ),
    ]
