# Generated by Django 5.2.15 on 2026-07-06 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('quizs', '0003_alter_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='quizs.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_tests', to='baseuser.baseuser')),
            ],
            options={
                'verbose_name': '🛒 Sotib olingan test',
                'verbose_name_plural': '🛒 Sotib olingan testlar',
                'indexes': [models.Index(fields=['user', 'test'], name='quizs_teste_user_id_8a8b7f_idx')],
                'unique_together': {('user', 'test')},
            },
        ),
    ]
