# Generated by Django 5.2.15 on 2026-07-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('quizs', '0004_testenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testenrollment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quizs.test'),
        ),
        migrations.AlterField(
            model_name='testenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_enrollments', to='baseuser.baseuser'),
        ),
    ]
