# Generated by Django 5.2.15 on 2026-07-07 11:53

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0005_alter_testenrollment_test_alter_testenrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=mdeditor.fields.MDTextField(help_text="Markdown formatida masalaning to'liq shartini yozing.", null=True, verbose_name='test sharti (Matn)'),
        ),
    ]
