# Generated by Django 5.2.15 on 2026-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0006_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='lifelines_used',
            field=models.PositiveIntegerField(default=0, help_text="Ushbu seansda foydalanuvchi hozirgacha ishlatgan lifeline'lar soni (faqat serverda hisoblanadi, frontend hisoblagichiga ishonilmaydi).", verbose_name='Ishlatilgan Reler (Lifeline) soni'),
        ),
    ]
