# Generated by Django 5.2.15 on 2026-07-12 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_total_tasks_count'),
        ('quizs', '0007_testsession_lifelines_used'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-id', 'created_at'], 'verbose_name': '❓ Savol', 'verbose_name_plural': '❔ Savollar'},
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='quizs_test_start_t_6316ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='quizs_test_is_acti_8de99b_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='quizs_test_modul_i_dfb4f0_idx',
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('test__isnull', True)), models.Q(('lesson__isnull', True), ('test__isnull', False)), _connector='OR'), name='question_belongs_to_lesson_xor_test'),
        ),
    ]
