# Generated by Django 5.2.15 on 2026-08-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lesson_completed', 'Dars yakunlandi'), ('module_completed', 'Bob yakunlandi'), ('course_completed', 'Kurs yakunlandi'), ('certificate_ready', 'Sertifikat tayyor'), ('new_lesson', 'Yangi dars'), ('achievement', 'Yutuq'), ('submission', 'Taqdimot natijasi'), ('contest_start', 'Musobaqa boshlanishi'), ('contest_end', 'Musobaqa tugashi'), ('system', 'Tizim xabari')], default='system', max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Havola')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name="Meta ma'lumotlar")),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilganmi")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
