# Generated by Django 5.2.15 on 2026-08-06 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        ('courses', '0001_initial'),
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('course', 'Course'), ('test', 'Test'), ('contest', 'Contest'), ('default', 'Default')], db_index=True, default='default', max_length=20)),
                ('organization_name', models.CharField(default='CfM Contest', max_length=255)),
                ('verify_domain', models.CharField(default='platforma.uz', max_length=255)),
                ('congratulation_text', models.TextField(default='Muvaffaqiyatli tamomlaganlik uchun berildi.')),
                ('mentor_name', models.CharField(default='Platforma Mentori', max_length=150)),
                ('mentor_status', models.CharField(default='Mentor', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/logos/%Y/%m/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/%Y/%m/')),
                ('background', models.ImageField(blank=True, null=True, upload_to='certificates/backgrounds/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('template_type',), name='unique_active_certificate_template')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qr/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='contests.contest')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='courses.course')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='quizs.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='baseuser.baseuser')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificate.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('course__isnull', False), ('test__isnull', False), ('contest__isnull', False), _connector='OR'), name='certificate_has_source')],
            },
        ),
    ]
