# Generated by Django 5.2.15 on 2026-06-28 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        ('courses', '0001_initial'),
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shablon nomi')),
                ('template_type', models.CharField(choices=[('course', 'Kurs uchun'), ('test', 'Test (Imtihon) uchun'), ('contest', 'Musobaqa uchun'), ('default', 'Umumiy shablon')], db_index=True, default='default', max_length=20, unique=True, verbose_name='Shablon turi')),
                ('organization_name', models.CharField(default='Platforma.uz', max_length=255, verbose_name='Tashkilot nomi')),
                ('verify_domain', models.CharField(default='platforma.uz', max_length=255, verbose_name='Tekshiruv domen')),
                ('congratulation_text', models.TextField(default='Muvaffaqiyatli tamomlaganlik uchun berildi.', verbose_name='Tabrik matni')),
                ('mentor_name', models.CharField(default='cfm', max_length=150, verbose_name='Mentor ismi')),
                ('mentor_status', models.CharField(default='Kurs Mentori', max_length=150, verbose_name='Mentor lavozimi')),
                ('mentor_signature', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/%Y/%m/', verbose_name='Mentor imzosi (PNG)')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='certificates/logos/%Y/%m/', verbose_name='Platforma logotipi')),
                ('illustration_image', models.ImageField(blank=True, null=True, upload_to='certificates/illustrations/%Y/%m/', verbose_name='Bezak rasmi')),
            ],
            options={
                'verbose_name': 'Sertifikat Sozlamasi',
                'verbose_name_plural': 'Sertifikat Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Sertifikat kodi')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/%Y/%m/', verbose_name='QR Kod')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/%Y/%m/', verbose_name='PDF Fayl')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqti')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_contest_certificates', to='contests.contest')),
                ('contest_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificate', to='contests.contestregistration')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='courses.course')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_test_certificates', to='quizs.test')),
                ('test_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_test_certificate', to='quizs.testsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='baseuser.baseuser')),
            ],
            options={
                'verbose_name': 'Berilgan Sertifikat',
                'verbose_name_plural': 'Berilgan Sertifikatlar',
                'ordering': ['-issued_at'],
            },
        ),
    ]
