# Generated by Django 5.2.15 on 2026-08-28 12:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('contests', '0001_initial'),
        ('courses', '0001_initial'),
        ('quizs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Summa (UZS)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan'), ('refunded', 'Qaytarilgan')], db_index=True, default='pending', max_length=20, verbose_name='Holati')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum'), ('paynet', 'Paynet')], db_index=True, max_length=20, verbose_name="To'lov tizimi")),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Provider transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contests.contest')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='courses.course')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='quizs.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '🧾 Invoice',
                'verbose_name_plural': '🧾 Invoicelar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payment_inv_user_id_8af95b_idx'), models.Index(fields=['provider', 'status'], name='payment_inv_provide_0292ef_idx'), models.Index(fields=['transaction_id'], name='payment_inv_transac_921af2_idx')],
            },
        ),
    ]
