# Generated by Django 5.2.15 on 2026-08-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('courses', '0001_initial'),
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('xp', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Jami XP')),
                ('level', models.CharField(choices=[('beginner', 'Yangi boshlovchi'), ('bronze', 'Bronza'), ('silver', 'Kumush'), ('gold', 'Oltin'), ('platinum', 'Platina'), ('emerald', 'Zumrad'), ('diamond', 'Olmos'), ('master', 'Master'), ('grandmaster', 'Grandmaster'), ('immortal', 'Immortal')], db_index=True, default='beginner', max_length=20, verbose_name='Daraja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📊 Foydalanuvchi statistikasi',
                'verbose_name_plural': '📊 Foydalanuvchilar statistikasi',
                'ordering': ['-xp'],
            },
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_modules', models.PositiveSmallIntegerField(default=0, verbose_name='Tugatilgan modullar soni')),
                ('completed_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='Tugatilgan darslar soni')),
                ('completed_tests', models.PositiveSmallIntegerField(default=0, verbose_name='Tugatilgan testlar soni')),
                ('completed_problems', models.PositiveSmallIntegerField(default=0, verbose_name='Yechilgan masalalar soni')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Tugallangan')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='courses.course', verbose_name='Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_statuses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '🏆 Kurs holati',
                'verbose_name_plural': '🏆 Kurslar holati',
                'indexes': [models.Index(fields=['user', 'course', 'is_completed'], name='status_cour_user_id_a45650_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LectureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text="Foydalanuvchi ma'ruzani birinchi marta ochgan vaqt.", null=True, verbose_name='Boshlangan vaqti')),
                ('last_position', models.PositiveIntegerField(default=0, help_text="Video qayerda to'xtaganini eslab qolish uchun (resume uchun).", verbose_name='Oxirgi video pozitsiyasi (soniya)')),
                ('watch_seconds', models.PositiveIntegerField(default=0, help_text="Analytics uchun: foydalanuvchi videoni jami necha soniya ko'rgan.", verbose_name="Ko'rilgan umumiy vaqt (soniya)")),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text="Agar talaba ma'ruzani o'qib bo'lib yoki videoni ko'rib 'Tugatdim' tugmasini bossa True bo'ladi.", verbose_name='Tugatilgan (✓)')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('lecture', models.ForeignKey(help_text="Foydalanuvchi o'qib yoki ko'rib tugatgan ma'ruza bloki.", on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='courses.lecture', verbose_name="Ma'ruza / Video blok")),
                ('user', models.ForeignKey(help_text="Tizimda faol bo'lgan talaba.", on_delete=django.db.models.deletion.CASCADE, related_name='lecture_statuses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "📝 Ma'ruza progress holati",
                'verbose_name_plural': "📝 Ma'ruza progress holatlari",
                'indexes': [models.Index(fields=['user', 'lecture', 'is_completed'], name='status_lect_user_id_f0983e_idx'), models.Index(fields=['is_completed', '-completed_at'], name='status_lect_is_comp_836c9a_idx')],
                'unique_together': {('user', 'lecture')},
            },
        ),
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='Foydalanuvchi darsni birinchi marta ochgan vaqt.', null=True, verbose_name='Boshlangan vaqti')),
                ('finished_tasks_count', models.PositiveSmallIntegerField(default=0, help_text='Ushbu dars ichida muvaffaqiyatli yakunlangan amaliy masalalar soni.', verbose_name='Tugatilgan vazifalar soni')),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text="Dars to'liq o'zlashtirildi deb hisoblanishi uchun belgi.", verbose_name='Tugallangan')),
                ('completed_at', models.DateTimeField(blank=True, help_text="Dars to'liq yakunlangan aniq sana va vaqt.", null=True, verbose_name='Tugatilgan vaqti')),
                ('lesson', models.ForeignKey(help_text='Holati kuzatilayotgan dars.', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='courses.lesson', verbose_name='Darslik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📗 Dars holati',
                'verbose_name_plural': '📗 Darslar holati',
                'indexes': [models.Index(fields=['user', 'lesson', 'is_completed'], name='status_less_user_id_976cec_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.PositiveSmallIntegerField(default=0, verbose_name='Tugatilgan darslar soni')),
                ('completed_tests', models.PositiveSmallIntegerField(default=0, verbose_name='Tugatilgan testlar soni')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Tugallangan')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan vaqti')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='courses.modul', verbose_name='Modul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_statuses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📚 Modul holati',
                'verbose_name_plural': '📚 Modullar holati',
                'indexes': [models.Index(fields=['user', 'modul', 'is_completed'], name='status_modu_user_id_fbb4e4_idx')],
                'unique_together': {('user', 'modul')},
            },
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(db_index=True, default=False, help_text="Ushbu masala kamida bir marta Accepted bo'lganmi?", verbose_name='Yechilgan')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Ushbu masala uchun yuborilgan barcha submissionlar soni.', verbose_name='Urinishlar soni')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Birinchi urinish vaqti')),
                ('solved_at', models.DateTimeField(blank=True, null=True, verbose_name='Yechilgan vaqti')),
                ('best_submission', models.ForeignKey(blank=True, help_text='Eng tez/eng samarali Accepted submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_status', to='submissions.submission', verbose_name='Eng yaxshi yechim')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='problems.problem', verbose_name='Masala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statuses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '🧩 Masala holati',
                'verbose_name_plural': '🧩 Masalalar holati',
                'indexes': [models.Index(fields=['user', 'solved'], name='status_prob_user_id_afe534_idx'), models.Index(fields=['problem', 'solved'], name='status_prob_problem_0d60b5_idx')],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text="Tizimdagi faollik sodir bo'lgan kun.", verbose_name='Sana')),
                ('xp_earned', models.PositiveIntegerField(default=0, help_text='Aynan shu sana doirasida foydalanuvchi ishlagan jami ball.', verbose_name='Kunlik XP')),
                ('tasks_count', models.PositiveIntegerField(default=0, help_text="Shu kunda to'g'ri yechilgan masalalar va test savollari soni.", verbose_name='Vazifalar soni')),
                ('total_duration', models.PositiveIntegerField(default=0, help_text="Shu kuni dars va testlarda o'tkazilgan jami vaqt miqdori.", verbose_name='Sarflangan umumiy vaqt (daqiqa)')),
                ('user', models.ForeignKey(help_text='Kunlik faollik qayd etilgan talaba.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📅 Kunlik Faollik (Heatmap)',
                'verbose_name_plural': '📅 Kunlik Faolliklar (Heatmap)',
                'indexes': [models.Index(fields=['user', 'date'], name='status_user_user_id_9158ad_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
