# Generated by Django 5.2.15 on 2026-06-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseuser', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('xp', models.PositiveIntegerField(db_index=True, default=0, help_text="Foydalanuvchi tomonidan platformada to'plangan jami umumiy ball (XP).", verbose_name="Jami to'plangan XP")),
                ('level', models.CharField(choices=[('beginner', 'Yangi boshlovchi'), ('bronze', 'Bronza'), ('silver', 'Kumush'), ('gold', 'Oltin'), ('pro', 'Professional')], db_index=True, default='beginner', help_text='Foydalanuvchining jami XP ballariga qarab avtomatik hisoblanadigan unvoni.', max_length=20, verbose_name='Joriy darajasi')),
                ('user', models.OneToOneField(help_text="Ushbu statistika egasi bo'lgan foydalanuvchi.", on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📊 Foydalanuvchi Statistikasi',
                'verbose_name_plural': '📊 Foydalanuvchilar Statistikasi',
                'ordering': ['-xp'],
            },
        ),
        migrations.CreateModel(
            name='LectureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=True, help_text="Agar talaba ma'ruzani o'qib bo'lib yoki videoni ko'rib 'Tugatdim' tugmasini bossa True bo'ladi.", verbose_name='Tugatilgan (✓)')),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tugatilgan vaqti')),
                ('lecture', models.ForeignKey(help_text="Foydalanuvchi o'qib yoki ko'rib tugatgan ma'ruza bloki.", on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='courses.lecture', verbose_name="Ma'ruza / Video blok")),
                ('user', models.ForeignKey(help_text="Tizimda faol bo'lgan talaba.", on_delete=django.db.models.deletion.CASCADE, related_name='lecture_statuses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "📝 Ma'ruza progress holati",
                'verbose_name_plural': "📝 Ma'ruza progress holatlari",
                'indexes': [models.Index(fields=['user', 'lecture', 'is_completed'], name='status_lect_user_id_f0983e_idx'), models.Index(fields=['is_completed', '-completed_at'], name='status_lect_is_comp_836c9a_idx')],
                'unique_together': {('user', 'lecture')},
            },
        ),
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_tasks_count', models.PositiveSmallIntegerField(default=0, help_text='Ushbu dars ichida muvaffaqiyatli yakunlangan amaliy masalalar soni.', verbose_name='Tugatilgan vazifalar soni')),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text="Dars to'liq o'zlashtirildi deb hisoblanishi uchun belgi.", verbose_name='Tugallangan')),
                ('completed_at', models.DateTimeField(blank=True, help_text="Dars to'liq yakunlangan aniq sana va vaqt.", null=True, verbose_name='Tugatilgan vaqti')),
                ('lesson', models.ForeignKey(help_text='Holati kuzatilayotgan dars.', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='courses.lesson', verbose_name='Darslik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📗 Dars holati',
                'verbose_name_plural': '📗 Darslar holati',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text="Tizimdagi faollik sodir bo'lgan kun.", verbose_name='Sana')),
                ('xp_earned', models.PositiveIntegerField(default=0, help_text='Aynan shu sana doirasida foydalanuvchi ishlagan jami ball.', verbose_name='Kunlik XP')),
                ('tasks_count', models.PositiveIntegerField(default=0, help_text="Shu kunda to'g'ri yechilgan masalalar va test savollari soni.", verbose_name='Vazifalar soni')),
                ('total_duration', models.PositiveIntegerField(default=0, help_text="Shu kuni dars va testlarda o'tkazilgan jami vaqt miqdori.", verbose_name='Sarflangan umumiy vaqt (daqiqa)')),
                ('user', models.ForeignKey(help_text='Kunlik faollik qayd etilgan talaba.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_days', to='baseuser.baseuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '📅 Kunlik Faollik (Heatmap)',
                'verbose_name_plural': '📅 Kunlik Faolliklar (Heatmap)',
                'indexes': [models.Index(fields=['user', 'date'], name='status_user_user_id_9158ad_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
