# Generated by Django 5.2.15 on 2026-06-28 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': '👤 Foydalanuvchi',
                'verbose_name_plural': '👥 Foydalanuvchilar',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Django default user (Admin/Teacher)')),
                ('student_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='baseuser.baseuser', verbose_name='Talaba (BaseUser)')),
            ],
            options={
                'verbose_name': '👤 Profil',
                'verbose_name_plural': '👤 Profillar',
                'db_table': 'user_profiles',
            },
        ),
    ]
