# Generated by Django 6.0.2 on 2026-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism")),
                ('session_id', models.IntegerField(blank=True, null=True, verbose_name='Session ID')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret Key')),
                ('iat', models.IntegerField(blank=True, help_text='JWT tokenning issued at timestampi', null=True, verbose_name='Token issued at')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': '👤 Foydalanuvchi',
                'verbose_name_plural': '👥 Foydalanuvchilar',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
