# Generated by Django 5.2.15 on 2026-08-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseuser', '0001_initial'),
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='center',
            field=models.ForeignKey(blank=True, help_text="Xodim biriktirilgan o'quv markazi. Bo'sh qoldirilsa (masalan superuser/Direktor uchun), admin panelida markaz maydonlarini har safar qo'lda tanlash talab qilinadi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='centers.center', verbose_name='Ish joyi (Markaz)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Django foydalanuvchi (Admin/Xodim)'),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['center', 'is_active'], name='users_center__185469_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('django_user__isnull', False), ('student_user__isnull', True)), models.Q(('django_user__isnull', True), ('student_user__isnull', False)), models.Q(('django_user__isnull', True), ('student_user__isnull', True)), _connector='OR'), name='profile_django_user_xor_student_user', violation_error_message="Profil FAQAT django_user GA yoki FAQAT student_user GA tegishli bo'lishi mumkin, ikkalasiga birdan emas."),
        ),
    ]
